/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAdminaccount extends Serializable {

    /**
     * Setter for <code>Recruitment.AdminAccount.account</code>. 管理员账号
     */
    public void setAccount(String value);

    /**
     * Getter for <code>Recruitment.AdminAccount.account</code>. 管理员账号
     */
    public String getAccount();

    /**
     * Setter for <code>Recruitment.AdminAccount.name</code>. 名称
     */
    public void setName(String value);

    /**
     * Getter for <code>Recruitment.AdminAccount.name</code>. 名称
     */
    public String getName();

    /**
     * Setter for <code>Recruitment.AdminAccount.password</code>. 密码
     */
    public void setPassword(String value);

    /**
     * Getter for <code>Recruitment.AdminAccount.password</code>. 密码
     */
    public String getPassword();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IAdminaccount
     */
    public void from(IAdminaccount from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IAdminaccount
     */
    public <E extends IAdminaccount> E into(E into);
}
