/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICompanyaccount extends Serializable {

    /**
     * Setter for <code>Recruitment.CompanyAccount.account</code>. 账号
     */
    public void setAccount(String value);

    /**
     * Getter for <code>Recruitment.CompanyAccount.account</code>. 账号
     */
    public String getAccount();

    /**
     * Setter for <code>Recruitment.CompanyAccount.name</code>. 企业名
     */
    public void setName(String value);

    /**
     * Getter for <code>Recruitment.CompanyAccount.name</code>. 企业名
     */
    public String getName();

    /**
     * Setter for <code>Recruitment.CompanyAccount.password</code>. 密码
     */
    public void setPassword(String value);

    /**
     * Getter for <code>Recruitment.CompanyAccount.password</code>. 密码
     */
    public String getPassword();

    /**
     * Setter for <code>Recruitment.CompanyAccount.url</code>. 企业网址
     */
    public void setUrl(String value);

    /**
     * Getter for <code>Recruitment.CompanyAccount.url</code>. 企业网址
     */
    public String getUrl();

    /**
     * Setter for <code>Recruitment.CompanyAccount.description</code>. 描述
     */
    public void setDescription(String value);

    /**
     * Getter for <code>Recruitment.CompanyAccount.description</code>. 描述
     */
    public String getDescription();

    /**
     * Setter for <code>Recruitment.CompanyAccount.tele</code>. 电话
     */
    public void setTele(String value);

    /**
     * Getter for <code>Recruitment.CompanyAccount.tele</code>. 电话
     */
    public String getTele();

    /**
     * Setter for <code>Recruitment.CompanyAccount.avatarUrl</code>. 头像
     */
    public void setAvatarurl(String value);

    /**
     * Getter for <code>Recruitment.CompanyAccount.avatarUrl</code>. 头像
     */
    public String getAvatarurl();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICompanyaccount
     */
    public void from(ICompanyaccount from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICompanyaccount
     */
    public <E extends ICompanyaccount> E into(E into);
}
