/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IComment extends Serializable {

    /**
     * Setter for <code>Recruitment.Comment.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>Recruitment.Comment.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>Recruitment.Comment.jobOfferId</code>. 外键对应（JobOffer：id)
     */
    public void setJobofferid(Integer value);

    /**
     * Getter for <code>Recruitment.Comment.jobOfferId</code>. 外键对应（JobOffer：id)
     */
    public Integer getJobofferid();

    /**
     * Setter for <code>Recruitment.Comment.accountType</code>. 1为企业，2为管理员，3为用户
     */
    public void setAccounttype(Integer value);

    /**
     * Getter for <code>Recruitment.Comment.accountType</code>. 1为企业，2为管理员，3为用户
     */
    public Integer getAccounttype();

    /**
     * Setter for <code>Recruitment.Comment.accountId</code>. 评论者id 对应（UserAccount:account)
     */
    public void setAccountid(String value);

    /**
     * Getter for <code>Recruitment.Comment.accountId</code>. 评论者id 对应（UserAccount:account)
     */
    public String getAccountid();

    /**
     * Setter for <code>Recruitment.Comment.responseId</code>. 回复者id 对应（UserAccount:account)
     */
    public void setResponseid(Integer value);

    /**
     * Getter for <code>Recruitment.Comment.responseId</code>. 回复者id 对应（UserAccount:account)
     */
    public Integer getResponseid();

    /**
     * Setter for <code>Recruitment.Comment.time</code>. 评论或回复时间
     */
    public void setTime(LocalDateTime value);

    /**
     * Getter for <code>Recruitment.Comment.time</code>. 评论或回复时间
     */
    public LocalDateTime getTime();

    /**
     * Setter for <code>Recruitment.Comment.content</code>. 评论或回复内容
     */
    public void setContent(String value);

    /**
     * Getter for <code>Recruitment.Comment.content</code>. 评论或回复内容
     */
    public String getContent();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IComment
     */
    public void from(IComment from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IComment
     */
    public <E extends IComment> E into(E into);
}
