/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IEducation extends Serializable {

    /**
     * Setter for <code>Recruitment.Education.key</code>.
     */
    public void setKey(Integer value);

    /**
     * Getter for <code>Recruitment.Education.key</code>.
     */
    public Integer getKey();

    /**
     * Setter for <code>Recruitment.Education.value</code>.
     */
    public void setValue(String value);

    /**
     * Getter for <code>Recruitment.Education.value</code>.
     */
    public String getValue();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IEducation
     */
    public void from(IEducation from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IEducation
     */
    public <E extends IEducation> E into(E into);
}
