/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IHomepush extends Serializable {

    /**
     * Setter for <code>Recruitment.HomePush.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>Recruitment.HomePush.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>Recruitment.HomePush.jobOffer</code>. 外键对应（jobOffer:id)
     */
    public void setJoboffer(Integer value);

    /**
     * Getter for <code>Recruitment.HomePush.jobOffer</code>. 外键对应（jobOffer:id)
     */
    public Integer getJoboffer();

    /**
     * Setter for <code>Recruitment.HomePush.handleAdminId</code>. 外键对应（AdminAccount:account)
     */
    public void setHandleadminid(String value);

    /**
     * Getter for <code>Recruitment.HomePush.handleAdminId</code>. 外键对应（AdminAccount:account)
     */
    public String getHandleadminid();

    /**
     * Setter for <code>Recruitment.HomePush.priority</code>. 优先级 数字越大优先级越低
     */
    public void setPriority(Integer value);

    /**
     * Getter for <code>Recruitment.HomePush.priority</code>. 优先级 数字越大优先级越低
     */
    public Integer getPriority();

    /**
     * Setter for <code>Recruitment.HomePush.endtime</code>. 截至推送日期
     */
    public void setEndtime(LocalDateTime value);

    /**
     * Getter for <code>Recruitment.HomePush.endtime</code>. 截至推送日期
     */
    public LocalDateTime getEndtime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IHomepush
     */
    public void from(IHomepush from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IHomepush
     */
    public <E extends IHomepush> E into(E into);
}
