/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IHomepushapplication extends Serializable {

    /**
     * Setter for <code>Recruitment.HomePushApplication.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>Recruitment.HomePushApplication.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>Recruitment.HomePushApplication.companyId</code>. 外键关联（CompanyAccount:account)
     */
    public void setCompanyid(String value);

    /**
     * Getter for <code>Recruitment.HomePushApplication.companyId</code>. 外键关联（CompanyAccount:account)
     */
    public String getCompanyid();

    /**
     * Setter for <code>Recruitment.HomePushApplication.endtime</code>. 申请截止时间
     */
    public void setEndtime(LocalDateTime value);

    /**
     * Getter for <code>Recruitment.HomePushApplication.endtime</code>. 申请截止时间
     */
    public LocalDateTime getEndtime();

    /**
     * Setter for <code>Recruitment.HomePushApplication.handleAdminId</code>. 处理该消息的管理员Id，空表示无人处理
     */
    public void setHandleadminid(String value);

    /**
     * Getter for <code>Recruitment.HomePushApplication.handleAdminId</code>. 处理该消息的管理员Id，空表示无人处理
     */
    public String getHandleadminid();

    /**
     * Setter for <code>Recruitment.HomePushApplication.handleTime</code>. 处理时间
     */
    public void setHandletime(LocalDateTime value);

    /**
     * Getter for <code>Recruitment.HomePushApplication.handleTime</code>. 处理时间
     */
    public LocalDateTime getHandletime();

    /**
     * Setter for <code>Recruitment.HomePushApplication.handleRes</code>. 处理结果（0表示不通过，1表示通过）
     */
    public void setHandleres(Integer value);

    /**
     * Getter for <code>Recruitment.HomePushApplication.handleRes</code>. 处理结果（0表示不通过，1表示通过）
     */
    public Integer getHandleres();

    /**
     * Setter for <code>Recruitment.HomePushApplication.handleResponseContent</code>. 处理人的处理批复
     */
    public void setHandleresponsecontent(String value);

    /**
     * Getter for <code>Recruitment.HomePushApplication.handleResponseContent</code>. 处理人的处理批复
     */
    public String getHandleresponsecontent();

    /**
     * Setter for <code>Recruitment.HomePushApplication.hasReadByCompany</code>. 是否被企业查看（0表示未查看，1表示已查看）
     */
    public void setHasreadbycompany(Integer value);

    /**
     * Getter for <code>Recruitment.HomePushApplication.hasReadByCompany</code>. 是否被企业查看（0表示未查看，1表示已查看）
     */
    public Integer getHasreadbycompany();

    /**
     * Setter for <code>Recruitment.HomePushApplication.jobOfferId</code>. 想要申请的招聘号，外键对应（JobOffer:id)
     */
    public void setJobofferid(Integer value);

    /**
     * Getter for <code>Recruitment.HomePushApplication.jobOfferId</code>. 想要申请的招聘号，外键对应（JobOffer:id)
     */
    public Integer getJobofferid();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IHomepushapplication
     */
    public void from(IHomepushapplication from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IHomepushapplication
     */
    public <E extends IHomepushapplication> E into(E into);
}
