/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IJoboffer extends Serializable {

    /**
     * Setter for <code>Recruitment.JobOffer.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>Recruitment.JobOffer.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>Recruitment.JobOffer.company</code>. 外键对应（CompanyAccount:account)
     */
    public void setCompany(String value);

    /**
     * Getter for <code>Recruitment.JobOffer.company</code>. 外键对应（CompanyAccount:account)
     */
    public String getCompany();

    /**
     * Setter for <code>Recruitment.JobOffer.professionType</code>. 职业类别
     */
    public void setProfessiontype(String value);

    /**
     * Getter for <code>Recruitment.JobOffer.professionType</code>. 职业类别
     */
    public String getProfessiontype();

    /**
     * Setter for <code>Recruitment.JobOffer.title</code>. 标题
     */
    public void setTitle(String value);

    /**
     * Getter for <code>Recruitment.JobOffer.title</code>. 标题
     */
    public String getTitle();

    /**
     * Setter for <code>Recruitment.JobOffer.description</code>. 描述
     */
    public void setDescription(String value);

    /**
     * Getter for <code>Recruitment.JobOffer.description</code>. 描述
     */
    public String getDescription();

    /**
     * Setter for <code>Recruitment.JobOffer.isDeleted</code>. 是否被删除
     */
    public void setIsdeleted(Integer value);

    /**
     * Getter for <code>Recruitment.JobOffer.isDeleted</code>. 是否被删除
     */
    public Integer getIsdeleted();

    /**
     * Setter for <code>Recruitment.JobOffer.startTime</code>. 开始时间
     */
    public void setStarttime(LocalDateTime value);

    /**
     * Getter for <code>Recruitment.JobOffer.startTime</code>. 开始时间
     */
    public LocalDateTime getStarttime();

    /**
     * Setter for <code>Recruitment.JobOffer.city</code>. 所在城市
     */
    public void setCity(String value);

    /**
     * Getter for <code>Recruitment.JobOffer.city</code>. 所在城市
     */
    public String getCity();

    /**
     * Setter for <code>Recruitment.JobOffer.endTime</code>. 结束时间
     */
    public void setEndtime(LocalDateTime value);

    /**
     * Getter for <code>Recruitment.JobOffer.endTime</code>. 结束时间
     */
    public LocalDateTime getEndtime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IJoboffer
     */
    public void from(IJoboffer from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IJoboffer
     */
    public <E extends IJoboffer> E into(E into);
}
