/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IResume extends Serializable {

    /**
     * Setter for <code>Recruitment.Resume.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>Recruitment.Resume.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>Recruitment.Resume.userid</code>. 外键（对应UserAccount:account)
     */
    public void setUserid(String value);

    /**
     * Getter for <code>Recruitment.Resume.userid</code>. 外键（对应UserAccount:account)
     */
    public String getUserid();

    /**
     * Setter for <code>Recruitment.Resume.jobId</code>. 外键对应（JobOffer：id)
     */
    public void setJobid(Integer value);

    /**
     * Getter for <code>Recruitment.Resume.jobId</code>. 外键对应（JobOffer：id)
     */
    public Integer getJobid();

    /**
     * Setter for <code>Recruitment.Resume.name</code>. 真实姓名
     */
    public void setName(String value);

    /**
     * Getter for <code>Recruitment.Resume.name</code>. 真实姓名
     */
    public String getName();

    /**
     * Setter for <code>Recruitment.Resume.sex</code>. 性别
     */
    public void setSex(Integer value);

    /**
     * Getter for <code>Recruitment.Resume.sex</code>. 性别
     */
    public Integer getSex();

    /**
     * Setter for <code>Recruitment.Resume.school</code>. 毕业学校
     */
    public void setSchool(String value);

    /**
     * Getter for <code>Recruitment.Resume.school</code>. 毕业学校
     */
    public String getSchool();

    /**
     * Setter for <code>Recruitment.Resume.graduationYear</code>. 毕业年份
     */
    public void setGraduationyear(Integer value);

    /**
     * Getter for <code>Recruitment.Resume.graduationYear</code>. 毕业年份
     */
    public Integer getGraduationyear();

    /**
     * Setter for <code>Recruitment.Resume.education</code>. 最高学历
     */
    public void setEducation(String value);

    /**
     * Getter for <code>Recruitment.Resume.education</code>. 最高学历
     */
    public String getEducation();

    /**
     * Setter for <code>Recruitment.Resume.city</code>. 所在城市
     */
    public void setCity(String value);

    /**
     * Getter for <code>Recruitment.Resume.city</code>. 所在城市
     */
    public String getCity();

    /**
     * Setter for <code>Recruitment.Resume.tele</code>. 电话
     */
    public void setTele(String value);

    /**
     * Getter for <code>Recruitment.Resume.tele</code>. 电话
     */
    public String getTele();

    /**
     * Setter for <code>Recruitment.Resume.email</code>. 邮箱
     */
    public void setEmail(String value);

    /**
     * Getter for <code>Recruitment.Resume.email</code>. 邮箱
     */
    public String getEmail();

    /**
     * Setter for <code>Recruitment.Resume.attatchmentUrl</code>. 可下载的简历附件
     */
    public void setAttatchmenturl(String value);

    /**
     * Getter for <code>Recruitment.Resume.attatchmentUrl</code>. 可下载的简历附件
     */
    public String getAttatchmenturl();

    /**
     * Setter for <code>Recruitment.Resume.state</code>. 状态
     */
    public void setState(String value);

    /**
     * Getter for <code>Recruitment.Resume.state</code>. 状态
     */
    public String getState();

    /**
     * Setter for <code>Recruitment.Resume.isPassed</code>. 0表示未通过，1表示通过，2表示还没结果
     */
    public void setIspassed(Integer value);

    /**
     * Getter for <code>Recruitment.Resume.isPassed</code>. 0表示未通过，1表示通过，2表示还没结果
     */
    public Integer getIspassed();

    /**
     * Setter for <code>Recruitment.Resume.stateTime</code>. 状态更新时间
     */
    public void setStatetime(LocalDateTime value);

    /**
     * Getter for <code>Recruitment.Resume.stateTime</code>. 状态更新时间
     */
    public LocalDateTime getStatetime();

    /**
     * Setter for <code>Recruitment.Resume.postTime</code>. 投递时间
     */
    public void setPosttime(LocalDateTime value);

    /**
     * Getter for <code>Recruitment.Resume.postTime</code>. 投递时间
     */
    public LocalDateTime getPosttime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IResume
     */
    public void from(IResume from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IResume
     */
    public <E extends IResume> E into(E into);
}
