/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUserdetailinfo extends Serializable {

    /**
     * Setter for <code>Recruitment.UserDetailInfo.account</code>. 用户账号
     */
    public void setAccount(String value);

    /**
     * Getter for <code>Recruitment.UserDetailInfo.account</code>. 用户账号
     */
    public String getAccount();

    /**
     * Setter for <code>Recruitment.UserDetailInfo.name</code>. 用户姓名
     */
    public void setName(String value);

    /**
     * Getter for <code>Recruitment.UserDetailInfo.name</code>. 用户姓名
     */
    public String getName();

    /**
     * Setter for <code>Recruitment.UserDetailInfo.sex</code>. 性别（0代表女，1代表男）
     */
    public void setSex(Integer value);

    /**
     * Getter for <code>Recruitment.UserDetailInfo.sex</code>. 性别（0代表女，1代表男）
     */
    public Integer getSex();

    /**
     * Setter for <code>Recruitment.UserDetailInfo.school</code>. 所在学校
     */
    public void setSchool(String value);

    /**
     * Getter for <code>Recruitment.UserDetailInfo.school</code>. 所在学校
     */
    public String getSchool();

    /**
     * Setter for <code>Recruitment.UserDetailInfo.graduationYear</code>. 毕业年份
     */
    public void setGraduationyear(Integer value);

    /**
     * Getter for <code>Recruitment.UserDetailInfo.graduationYear</code>. 毕业年份
     */
    public Integer getGraduationyear();

    /**
     * Setter for <code>Recruitment.UserDetailInfo.education</code>. 最高学历
     */
    public void setEducation(String value);

    /**
     * Getter for <code>Recruitment.UserDetailInfo.education</code>. 最高学历
     */
    public String getEducation();

    /**
     * Setter for <code>Recruitment.UserDetailInfo.tele</code>. 电话
     */
    public void setTele(String value);

    /**
     * Getter for <code>Recruitment.UserDetailInfo.tele</code>. 电话
     */
    public String getTele();

    /**
     * Setter for <code>Recruitment.UserDetailInfo.email</code>. 邮箱
     */
    public void setEmail(String value);

    /**
     * Getter for <code>Recruitment.UserDetailInfo.email</code>. 邮箱
     */
    public String getEmail();

    /**
     * Setter for <code>Recruitment.UserDetailInfo.city</code>.
     */
    public void setCity(String value);

    /**
     * Getter for <code>Recruitment.UserDetailInfo.city</code>.
     */
    public String getCity();

    /**
     * Setter for <code>Recruitment.UserDetailInfo.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>Recruitment.UserDetailInfo.description</code>.
     */
    public String getDescription();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUserdetailinfo
     */
    public void from(IUserdetailinfo from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUserdetailinfo
     */
    public <E extends IUserdetailinfo> E into(E into);
}
