/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUseraccont extends Serializable {

    /**
     * Setter for <code>Recruitment.UserAccont.account</code>. 账号
     */
    public void setAccount(String value);

    /**
     * Getter for <code>Recruitment.UserAccont.account</code>. 账号
     */
    public String getAccount();

    /**
     * Setter for <code>Recruitment.UserAccont.nickName</code>. 昵称（非真实姓名）
     */
    public void setNickname(String value);

    /**
     * Getter for <code>Recruitment.UserAccont.nickName</code>. 昵称（非真实姓名）
     */
    public String getNickname();

    /**
     * Setter for <code>Recruitment.UserAccont.password</code>. 密码
     */
    public void setPassword(String value);

    /**
     * Getter for <code>Recruitment.UserAccont.password</code>. 密码
     */
    public String getPassword();

    /**
     * Setter for <code>Recruitment.UserAccont.avatarUrl</code>. 头像
     */
    public void setAvatarurl(String value);

    /**
     * Getter for <code>Recruitment.UserAccont.avatarUrl</code>. 头像
     */
    public String getAvatarurl();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUseraccont
     */
    public void from(IUseraccont from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUseraccont
     */
    public <E extends IUseraccont> E into(E into);
}
