/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.pojos;


import com.doteadore.recruitment_backend.codegen.tables.interfaces.IAdminaccount;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Adminaccount implements IAdminaccount {

    private static final long serialVersionUID = -1743003957;

    private String account;
    private String name;
    private String password;

    public Adminaccount() {}

    public Adminaccount(IAdminaccount value) {
        this.account = value.getAccount();
        this.name = value.getName();
        this.password = value.getPassword();
    }

    public Adminaccount(
        String account,
        String name,
        String password
    ) {
        this.account = account;
        this.name = name;
        this.password = password;
    }

    @Override
    public String getAccount() {
        return this.account;
    }

    @Override
    public void setAccount(String account) {
        this.account = account;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Adminaccount (");

        sb.append(account);
        sb.append(", ").append(name);
        sb.append(", ").append(password);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAdminaccount from) {
        setAccount(from.getAccount());
        setName(from.getName());
        setPassword(from.getPassword());
    }

    @Override
    public <E extends IAdminaccount> E into(E into) {
        into.from(this);
        return into;
    }
}
