/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.pojos;


import com.doteadore.recruitment_backend.codegen.tables.interfaces.IComment;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comment implements IComment {

    private static final long serialVersionUID = -1967575402;

    private Integer       id;
    private Integer       jobofferid;
    private Integer       accpunttype;
    private String        accountid;
    private String        responseid;
    private LocalDateTime time;
    private String        content;

    public Comment() {}

    public Comment(IComment value) {
        this.id = value.getId();
        this.jobofferid = value.getJobofferid();
        this.accpunttype = value.getAccpunttype();
        this.accountid = value.getAccountid();
        this.responseid = value.getResponseid();
        this.time = value.getTime();
        this.content = value.getContent();
    }

    public Comment(
        Integer       id,
        Integer       jobofferid,
        Integer       accpunttype,
        String        accountid,
        String        responseid,
        LocalDateTime time,
        String        content
    ) {
        this.id = id;
        this.jobofferid = jobofferid;
        this.accpunttype = accpunttype;
        this.accountid = accountid;
        this.responseid = responseid;
        this.time = time;
        this.content = content;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public Integer getJobofferid() {
        return this.jobofferid;
    }

    @Override
    public void setJobofferid(Integer jobofferid) {
        this.jobofferid = jobofferid;
    }

    @Override
    public Integer getAccpunttype() {
        return this.accpunttype;
    }

    @Override
    public void setAccpunttype(Integer accpunttype) {
        this.accpunttype = accpunttype;
    }

    @Override
    public String getAccountid() {
        return this.accountid;
    }

    @Override
    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }

    @Override
    public String getResponseid() {
        return this.responseid;
    }

    @Override
    public void setResponseid(String responseid) {
        this.responseid = responseid;
    }

    @Override
    public LocalDateTime getTime() {
        return this.time;
    }

    @Override
    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    @Override
    public String getContent() {
        return this.content;
    }

    @Override
    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Comment (");

        sb.append(id);
        sb.append(", ").append(jobofferid);
        sb.append(", ").append(accpunttype);
        sb.append(", ").append(accountid);
        sb.append(", ").append(responseid);
        sb.append(", ").append(time);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IComment from) {
        setId(from.getId());
        setJobofferid(from.getJobofferid());
        setAccpunttype(from.getAccpunttype());
        setAccountid(from.getAccountid());
        setResponseid(from.getResponseid());
        setTime(from.getTime());
        setContent(from.getContent());
    }

    @Override
    public <E extends IComment> E into(E into) {
        into.from(this);
        return into;
    }
}
