/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.pojos;


import com.doteadore.recruitment_backend.codegen.tables.interfaces.ICompanyaccount;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Companyaccount implements ICompanyaccount {

    private static final long serialVersionUID = 1104270160;

    private String account;
    private String name;
    private String password;
    private String url;
    private String description;
    private String tele;
    private String avatarurl;

    public Companyaccount() {}

    public Companyaccount(ICompanyaccount value) {
        this.account = value.getAccount();
        this.name = value.getName();
        this.password = value.getPassword();
        this.url = value.getUrl();
        this.description = value.getDescription();
        this.tele = value.getTele();
        this.avatarurl = value.getAvatarurl();
    }

    public Companyaccount(
        String account,
        String name,
        String password,
        String url,
        String description,
        String tele,
        String avatarurl
    ) {
        this.account = account;
        this.name = name;
        this.password = password;
        this.url = url;
        this.description = description;
        this.tele = tele;
        this.avatarurl = avatarurl;
    }

    @Override
    public String getAccount() {
        return this.account;
    }

    @Override
    public void setAccount(String account) {
        this.account = account;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String getUrl() {
        return this.url;
    }

    @Override
    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String getTele() {
        return this.tele;
    }

    @Override
    public void setTele(String tele) {
        this.tele = tele;
    }

    @Override
    public String getAvatarurl() {
        return this.avatarurl;
    }

    @Override
    public void setAvatarurl(String avatarurl) {
        this.avatarurl = avatarurl;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Companyaccount (");

        sb.append(account);
        sb.append(", ").append(name);
        sb.append(", ").append(password);
        sb.append(", ").append(url);
        sb.append(", ").append(description);
        sb.append(", ").append(tele);
        sb.append(", ").append(avatarurl);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ICompanyaccount from) {
        setAccount(from.getAccount());
        setName(from.getName());
        setPassword(from.getPassword());
        setUrl(from.getUrl());
        setDescription(from.getDescription());
        setTele(from.getTele());
        setAvatarurl(from.getAvatarurl());
    }

    @Override
    public <E extends ICompanyaccount> E into(E into) {
        into.from(this);
        return into;
    }
}
