/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.pojos;


import com.doteadore.recruitment_backend.codegen.tables.interfaces.IResumestate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Resumestate implements IResumestate {

    private static final long serialVersionUID = 998979832;

    private Integer key;
    private String  value;

    public Resumestate() {}

    public Resumestate(IResumestate value) {
        this.key = value.getKey();
        this.value = value.getValue();
    }

    public Resumestate(
        Integer key,
        String  value
    ) {
        this.key = key;
        this.value = value;
    }

    @Override
    public Integer getKey() {
        return this.key;
    }

    @Override
    public void setKey(Integer key) {
        this.key = key;
    }

    @Override
    public String getValue() {
        return this.value;
    }

    @Override
    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Resumestate (");

        sb.append(key);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IResumestate from) {
        setKey(from.getKey());
        setValue(from.getValue());
    }

    @Override
    public <E extends IResumestate> E into(E into) {
        into.from(this);
        return into;
    }
}
