/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.pojos;


import com.doteadore.recruitment_backend.codegen.tables.interfaces.IResume;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Resume implements IResume {

    private static final long serialVersionUID = -1957047357;

    private Integer       id;
    private String        userid;
    private Integer       jobid;
    private String        name;
    private Integer       sex;
    private String        school;
    private Integer       graduationyear;
    private String        education;
    private String        city;
    private String        tele;
    private String        email;
    private String        attatchmenturl;
    private String        state;
    private Integer       ispassed;
    private LocalDateTime statetime;
    private LocalDateTime posttime;

    public Resume() {}

    public Resume(IResume value) {
        this.id = value.getId();
        this.userid = value.getUserid();
        this.jobid = value.getJobid();
        this.name = value.getName();
        this.sex = value.getSex();
        this.school = value.getSchool();
        this.graduationyear = value.getGraduationyear();
        this.education = value.getEducation();
        this.city = value.getCity();
        this.tele = value.getTele();
        this.email = value.getEmail();
        this.attatchmenturl = value.getAttatchmenturl();
        this.state = value.getState();
        this.ispassed = value.getIspassed();
        this.statetime = value.getStatetime();
        this.posttime = value.getPosttime();
    }

    public Resume(
        Integer       id,
        String        userid,
        Integer       jobid,
        String        name,
        Integer       sex,
        String        school,
        Integer       graduationyear,
        String        education,
        String        city,
        String        tele,
        String        email,
        String        attatchmenturl,
        String        state,
        Integer       ispassed,
        LocalDateTime statetime,
        LocalDateTime posttime
    ) {
        this.id = id;
        this.userid = userid;
        this.jobid = jobid;
        this.name = name;
        this.sex = sex;
        this.school = school;
        this.graduationyear = graduationyear;
        this.education = education;
        this.city = city;
        this.tele = tele;
        this.email = email;
        this.attatchmenturl = attatchmenturl;
        this.state = state;
        this.ispassed = ispassed;
        this.statetime = statetime;
        this.posttime = posttime;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String getUserid() {
        return this.userid;
    }

    @Override
    public void setUserid(String userid) {
        this.userid = userid;
    }

    @Override
    public Integer getJobid() {
        return this.jobid;
    }

    @Override
    public void setJobid(Integer jobid) {
        this.jobid = jobid;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public Integer getSex() {
        return this.sex;
    }

    @Override
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    @Override
    public String getSchool() {
        return this.school;
    }

    @Override
    public void setSchool(String school) {
        this.school = school;
    }

    @Override
    public Integer getGraduationyear() {
        return this.graduationyear;
    }

    @Override
    public void setGraduationyear(Integer graduationyear) {
        this.graduationyear = graduationyear;
    }

    @Override
    public String getEducation() {
        return this.education;
    }

    @Override
    public void setEducation(String education) {
        this.education = education;
    }

    @Override
    public String getCity() {
        return this.city;
    }

    @Override
    public void setCity(String city) {
        this.city = city;
    }

    @Override
    public String getTele() {
        return this.tele;
    }

    @Override
    public void setTele(String tele) {
        this.tele = tele;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String getAttatchmenturl() {
        return this.attatchmenturl;
    }

    @Override
    public void setAttatchmenturl(String attatchmenturl) {
        this.attatchmenturl = attatchmenturl;
    }

    @Override
    public String getState() {
        return this.state;
    }

    @Override
    public void setState(String state) {
        this.state = state;
    }

    @Override
    public Integer getIspassed() {
        return this.ispassed;
    }

    @Override
    public void setIspassed(Integer ispassed) {
        this.ispassed = ispassed;
    }

    @Override
    public LocalDateTime getStatetime() {
        return this.statetime;
    }

    @Override
    public void setStatetime(LocalDateTime statetime) {
        this.statetime = statetime;
    }

    @Override
    public LocalDateTime getPosttime() {
        return this.posttime;
    }

    @Override
    public void setPosttime(LocalDateTime posttime) {
        this.posttime = posttime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Resume (");

        sb.append(id);
        sb.append(", ").append(userid);
        sb.append(", ").append(jobid);
        sb.append(", ").append(name);
        sb.append(", ").append(sex);
        sb.append(", ").append(school);
        sb.append(", ").append(graduationyear);
        sb.append(", ").append(education);
        sb.append(", ").append(city);
        sb.append(", ").append(tele);
        sb.append(", ").append(email);
        sb.append(", ").append(attatchmenturl);
        sb.append(", ").append(state);
        sb.append(", ").append(ispassed);
        sb.append(", ").append(statetime);
        sb.append(", ").append(posttime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IResume from) {
        setId(from.getId());
        setUserid(from.getUserid());
        setJobid(from.getJobid());
        setName(from.getName());
        setSex(from.getSex());
        setSchool(from.getSchool());
        setGraduationyear(from.getGraduationyear());
        setEducation(from.getEducation());
        setCity(from.getCity());
        setTele(from.getTele());
        setEmail(from.getEmail());
        setAttatchmenturl(from.getAttatchmenturl());
        setState(from.getState());
        setIspassed(from.getIspassed());
        setStatetime(from.getStatetime());
        setPosttime(from.getPosttime());
    }

    @Override
    public <E extends IResume> E into(E into) {
        into.from(this);
        return into;
    }
}
