/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.pojos;


import com.doteadore.recruitment_backend.codegen.tables.interfaces.IUserdetailinfo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userdetailinfo implements IUserdetailinfo {

    private static final long serialVersionUID = -775304690;

    private String  account;
    private String  name;
    private Integer sex;
    private String  school;
    private Integer graduationyear;
    private String  education;
    private String  tele;
    private String  email;
    private String  city;
    private String  description;

    public Userdetailinfo() {}

    public Userdetailinfo(IUserdetailinfo value) {
        this.account = value.getAccount();
        this.name = value.getName();
        this.sex = value.getSex();
        this.school = value.getSchool();
        this.graduationyear = value.getGraduationyear();
        this.education = value.getEducation();
        this.tele = value.getTele();
        this.email = value.getEmail();
        this.city = value.getCity();
        this.description = value.getDescription();
    }

    public Userdetailinfo(
        String  account,
        String  name,
        Integer sex,
        String  school,
        Integer graduationyear,
        String  education,
        String  tele,
        String  email,
        String  city,
        String  description
    ) {
        this.account = account;
        this.name = name;
        this.sex = sex;
        this.school = school;
        this.graduationyear = graduationyear;
        this.education = education;
        this.tele = tele;
        this.email = email;
        this.city = city;
        this.description = description;
    }

    @Override
    public String getAccount() {
        return this.account;
    }

    @Override
    public void setAccount(String account) {
        this.account = account;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public Integer getSex() {
        return this.sex;
    }

    @Override
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    @Override
    public String getSchool() {
        return this.school;
    }

    @Override
    public void setSchool(String school) {
        this.school = school;
    }

    @Override
    public Integer getGraduationyear() {
        return this.graduationyear;
    }

    @Override
    public void setGraduationyear(Integer graduationyear) {
        this.graduationyear = graduationyear;
    }

    @Override
    public String getEducation() {
        return this.education;
    }

    @Override
    public void setEducation(String education) {
        this.education = education;
    }

    @Override
    public String getTele() {
        return this.tele;
    }

    @Override
    public void setTele(String tele) {
        this.tele = tele;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String getCity() {
        return this.city;
    }

    @Override
    public void setCity(String city) {
        this.city = city;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Userdetailinfo (");

        sb.append(account);
        sb.append(", ").append(name);
        sb.append(", ").append(sex);
        sb.append(", ").append(school);
        sb.append(", ").append(graduationyear);
        sb.append(", ").append(education);
        sb.append(", ").append(tele);
        sb.append(", ").append(email);
        sb.append(", ").append(city);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUserdetailinfo from) {
        setAccount(from.getAccount());
        setName(from.getName());
        setSex(from.getSex());
        setSchool(from.getSchool());
        setGraduationyear(from.getGraduationyear());
        setEducation(from.getEducation());
        setTele(from.getTele());
        setEmail(from.getEmail());
        setCity(from.getCity());
        setDescription(from.getDescription());
    }

    @Override
    public <E extends IUserdetailinfo> E into(E into) {
        into.from(this);
        return into;
    }
}
