/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.pojos;


import com.doteadore.recruitment_backend.codegen.tables.interfaces.IUseraccont;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Useraccont implements IUseraccont {

    private static final long serialVersionUID = -1313397504;

    private String account;
    private String nickname;
    private String password;
    private String avatarurl;

    public Useraccont() {}

    public Useraccont(IUseraccont value) {
        this.account = value.getAccount();
        this.nickname = value.getNickname();
        this.password = value.getPassword();
        this.avatarurl = value.getAvatarurl();
    }

    public Useraccont(
        String account,
        String nickname,
        String password,
        String avatarurl
    ) {
        this.account = account;
        this.nickname = nickname;
        this.password = password;
        this.avatarurl = avatarurl;
    }

    @Override
    public String getAccount() {
        return this.account;
    }

    @Override
    public void setAccount(String account) {
        this.account = account;
    }

    @Override
    public String getNickname() {
        return this.nickname;
    }

    @Override
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String getAvatarurl() {
        return this.avatarurl;
    }

    @Override
    public void setAvatarurl(String avatarurl) {
        this.avatarurl = avatarurl;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Useraccont (");

        sb.append(account);
        sb.append(", ").append(nickname);
        sb.append(", ").append(password);
        sb.append(", ").append(avatarurl);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUseraccont from) {
        setAccount(from.getAccount());
        setNickname(from.getNickname());
        setPassword(from.getPassword());
        setAvatarurl(from.getAvatarurl());
    }

    @Override
    public <E extends IUseraccont> E into(E into) {
        into.from(this);
        return into;
    }
}
