/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.records;


import com.doteadore.recruitment_backend.codegen.tables.Education;
import com.doteadore.recruitment_backend.codegen.tables.interfaces.IEducation;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EducationRecord extends UpdatableRecordImpl<EducationRecord> implements Record2<Integer, String>, IEducation {

    private static final long serialVersionUID = -497408817;

    /**
     * Setter for <code>Recruitment.Education.key</code>.
     */
    @Override
    public void setKey(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Recruitment.Education.key</code>.
     */
    @Override
    public Integer getKey() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Recruitment.Education.value</code>.
     */
    @Override
    public void setValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Recruitment.Education.value</code>.
     */
    @Override
    public String getValue() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Education.EDUCATION.KEY;
    }

    @Override
    public Field<String> field2() {
        return Education.EDUCATION.VALUE;
    }

    @Override
    public Integer component1() {
        return getKey();
    }

    @Override
    public String component2() {
        return getValue();
    }

    @Override
    public Integer value1() {
        return getKey();
    }

    @Override
    public String value2() {
        return getValue();
    }

    @Override
    public EducationRecord value1(Integer value) {
        setKey(value);
        return this;
    }

    @Override
    public EducationRecord value2(String value) {
        setValue(value);
        return this;
    }

    @Override
    public EducationRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IEducation from) {
        setKey(from.getKey());
        setValue(from.getValue());
    }

    @Override
    public <E extends IEducation> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EducationRecord
     */
    public EducationRecord() {
        super(Education.EDUCATION);
    }

    /**
     * Create a detached, initialised EducationRecord
     */
    public EducationRecord(Integer key, String value) {
        super(Education.EDUCATION);

        set(0, key);
        set(1, value);
    }
}
