/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.records;


import com.doteadore.recruitment_backend.codegen.tables.Homepushapplication;
import com.doteadore.recruitment_backend.codegen.tables.interfaces.IHomepushapplication;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HomepushapplicationRecord extends UpdatableRecordImpl<HomepushapplicationRecord> implements Record9<Integer, String, LocalDateTime, String, LocalDateTime, Integer, String, Integer, Integer>, IHomepushapplication {

    private static final long serialVersionUID = -1133218609;

    /**
     * Setter for <code>Recruitment.HomePushApplication.id</code>.
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Recruitment.HomePushApplication.id</code>.
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Recruitment.HomePushApplication.companyId</code>. 外键关联（CompanyAccount:account)
     */
    @Override
    public void setCompanyid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Recruitment.HomePushApplication.companyId</code>. 外键关联（CompanyAccount:account)
     */
    @Override
    public String getCompanyid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Recruitment.HomePushApplication.endtime</code>. 申请截止时间
     */
    @Override
    public void setEndtime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>Recruitment.HomePushApplication.endtime</code>. 申请截止时间
     */
    @Override
    public LocalDateTime getEndtime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>Recruitment.HomePushApplication.handleAdminId</code>. 处理该消息的管理员Id，空表示无人处理
     */
    @Override
    public void setHandleadminid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Recruitment.HomePushApplication.handleAdminId</code>. 处理该消息的管理员Id，空表示无人处理
     */
    @Override
    public String getHandleadminid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>Recruitment.HomePushApplication.handleTime</code>. 处理时间
     */
    @Override
    public void setHandletime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>Recruitment.HomePushApplication.handleTime</code>. 处理时间
     */
    @Override
    public LocalDateTime getHandletime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>Recruitment.HomePushApplication.handleRes</code>. 处理结果（0表示不通过，1表示通过）
     */
    @Override
    public void setHandleres(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>Recruitment.HomePushApplication.handleRes</code>. 处理结果（0表示不通过，1表示通过）
     */
    @Override
    public Integer getHandleres() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>Recruitment.HomePushApplication.handleResponseContent</code>. 处理人的处理批复
     */
    @Override
    public void setHandleresponsecontent(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>Recruitment.HomePushApplication.handleResponseContent</code>. 处理人的处理批复
     */
    @Override
    public String getHandleresponsecontent() {
        return (String) get(6);
    }

    /**
     * Setter for <code>Recruitment.HomePushApplication.hasReadByCompany</code>. 是否被企业查看（0表示未查看，1表示已查看）
     */
    @Override
    public void setHasreadbycompany(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>Recruitment.HomePushApplication.hasReadByCompany</code>. 是否被企业查看（0表示未查看，1表示已查看）
     */
    @Override
    public Integer getHasreadbycompany() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>Recruitment.HomePushApplication.jobOfferId</code>. 想要申请的招聘号，外键对应（JobOffer:id)
     */
    @Override
    public void setJobofferid(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>Recruitment.HomePushApplication.jobOfferId</code>. 想要申请的招聘号，外键对应（JobOffer:id)
     */
    @Override
    public Integer getJobofferid() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, LocalDateTime, String, LocalDateTime, Integer, String, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, LocalDateTime, String, LocalDateTime, Integer, String, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Homepushapplication.HOMEPUSHAPPLICATION.ID;
    }

    @Override
    public Field<String> field2() {
        return Homepushapplication.HOMEPUSHAPPLICATION.COMPANYID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Homepushapplication.HOMEPUSHAPPLICATION.ENDTIME;
    }

    @Override
    public Field<String> field4() {
        return Homepushapplication.HOMEPUSHAPPLICATION.HANDLEADMINID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Homepushapplication.HOMEPUSHAPPLICATION.HANDLETIME;
    }

    @Override
    public Field<Integer> field6() {
        return Homepushapplication.HOMEPUSHAPPLICATION.HANDLERES;
    }

    @Override
    public Field<String> field7() {
        return Homepushapplication.HOMEPUSHAPPLICATION.HANDLERESPONSECONTENT;
    }

    @Override
    public Field<Integer> field8() {
        return Homepushapplication.HOMEPUSHAPPLICATION.HASREADBYCOMPANY;
    }

    @Override
    public Field<Integer> field9() {
        return Homepushapplication.HOMEPUSHAPPLICATION.JOBOFFERID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCompanyid();
    }

    @Override
    public LocalDateTime component3() {
        return getEndtime();
    }

    @Override
    public String component4() {
        return getHandleadminid();
    }

    @Override
    public LocalDateTime component5() {
        return getHandletime();
    }

    @Override
    public Integer component6() {
        return getHandleres();
    }

    @Override
    public String component7() {
        return getHandleresponsecontent();
    }

    @Override
    public Integer component8() {
        return getHasreadbycompany();
    }

    @Override
    public Integer component9() {
        return getJobofferid();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCompanyid();
    }

    @Override
    public LocalDateTime value3() {
        return getEndtime();
    }

    @Override
    public String value4() {
        return getHandleadminid();
    }

    @Override
    public LocalDateTime value5() {
        return getHandletime();
    }

    @Override
    public Integer value6() {
        return getHandleres();
    }

    @Override
    public String value7() {
        return getHandleresponsecontent();
    }

    @Override
    public Integer value8() {
        return getHasreadbycompany();
    }

    @Override
    public Integer value9() {
        return getJobofferid();
    }

    @Override
    public HomepushapplicationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public HomepushapplicationRecord value2(String value) {
        setCompanyid(value);
        return this;
    }

    @Override
    public HomepushapplicationRecord value3(LocalDateTime value) {
        setEndtime(value);
        return this;
    }

    @Override
    public HomepushapplicationRecord value4(String value) {
        setHandleadminid(value);
        return this;
    }

    @Override
    public HomepushapplicationRecord value5(LocalDateTime value) {
        setHandletime(value);
        return this;
    }

    @Override
    public HomepushapplicationRecord value6(Integer value) {
        setHandleres(value);
        return this;
    }

    @Override
    public HomepushapplicationRecord value7(String value) {
        setHandleresponsecontent(value);
        return this;
    }

    @Override
    public HomepushapplicationRecord value8(Integer value) {
        setHasreadbycompany(value);
        return this;
    }

    @Override
    public HomepushapplicationRecord value9(Integer value) {
        setJobofferid(value);
        return this;
    }

    @Override
    public HomepushapplicationRecord values(Integer value1, String value2, LocalDateTime value3, String value4, LocalDateTime value5, Integer value6, String value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IHomepushapplication from) {
        setId(from.getId());
        setCompanyid(from.getCompanyid());
        setEndtime(from.getEndtime());
        setHandleadminid(from.getHandleadminid());
        setHandletime(from.getHandletime());
        setHandleres(from.getHandleres());
        setHandleresponsecontent(from.getHandleresponsecontent());
        setHasreadbycompany(from.getHasreadbycompany());
        setJobofferid(from.getJobofferid());
    }

    @Override
    public <E extends IHomepushapplication> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HomepushapplicationRecord
     */
    public HomepushapplicationRecord() {
        super(Homepushapplication.HOMEPUSHAPPLICATION);
    }

    /**
     * Create a detached, initialised HomepushapplicationRecord
     */
    public HomepushapplicationRecord(Integer id, String companyid, LocalDateTime endtime, String handleadminid, LocalDateTime handletime, Integer handleres, String handleresponsecontent, Integer hasreadbycompany, Integer jobofferid) {
        super(Homepushapplication.HOMEPUSHAPPLICATION);

        set(0, id);
        set(1, companyid);
        set(2, endtime);
        set(3, handleadminid);
        set(4, handletime);
        set(5, handleres);
        set(6, handleresponsecontent);
        set(7, hasreadbycompany);
        set(8, jobofferid);
    }
}
