/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.records;


import com.doteadore.recruitment_backend.codegen.tables.Joboffer;
import com.doteadore.recruitment_backend.codegen.tables.interfaces.IJoboffer;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobofferRecord extends UpdatableRecordImpl<JobofferRecord> implements Record10<Integer, String, Integer, String, String, Integer, LocalDateTime, String, LocalDateTime, Integer>, IJoboffer {

    private static final long serialVersionUID = 2007096593;

    /**
     * Setter for <code>Recruitment.JobOffer.id</code>.
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Recruitment.JobOffer.id</code>.
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Recruitment.JobOffer.company</code>. 外键对应（CompanyAccount:account)
     */
    @Override
    public void setCompany(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Recruitment.JobOffer.company</code>. 外键对应（CompanyAccount:account)
     */
    @Override
    public String getCompany() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Recruitment.JobOffer.professionType</code>. 职业类别
     */
    @Override
    public void setProfessiontype(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Recruitment.JobOffer.professionType</code>. 职业类别
     */
    @Override
    public Integer getProfessiontype() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>Recruitment.JobOffer.title</code>. 标题
     */
    @Override
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Recruitment.JobOffer.title</code>. 标题
     */
    @Override
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>Recruitment.JobOffer.description</code>. 描述
     */
    @Override
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>Recruitment.JobOffer.description</code>. 描述
     */
    @Override
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>Recruitment.JobOffer.isDeleted</code>. 是否被删除
     */
    @Override
    public void setIsdeleted(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>Recruitment.JobOffer.isDeleted</code>. 是否被删除
     */
    @Override
    public Integer getIsdeleted() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>Recruitment.JobOffer.startTime</code>. 开始时间
     */
    @Override
    public void setStarttime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>Recruitment.JobOffer.startTime</code>. 开始时间
     */
    @Override
    public LocalDateTime getStarttime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>Recruitment.JobOffer.city</code>. 所在城市
     */
    @Override
    public void setCity(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>Recruitment.JobOffer.city</code>. 所在城市
     */
    @Override
    public String getCity() {
        return (String) get(7);
    }

    /**
     * Setter for <code>Recruitment.JobOffer.endTime</code>. 结束时间
     */
    @Override
    public void setEndtime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>Recruitment.JobOffer.endTime</code>. 结束时间
     */
    @Override
    public LocalDateTime getEndtime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>Recruitment.JobOffer.position</code>.
     */
    @Override
    public void setPosition(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>Recruitment.JobOffer.position</code>.
     */
    @Override
    public Integer getPosition() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, Integer, String, String, Integer, LocalDateTime, String, LocalDateTime, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, Integer, String, String, Integer, LocalDateTime, String, LocalDateTime, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Joboffer.JOBOFFER.ID;
    }

    @Override
    public Field<String> field2() {
        return Joboffer.JOBOFFER.COMPANY;
    }

    @Override
    public Field<Integer> field3() {
        return Joboffer.JOBOFFER.PROFESSIONTYPE;
    }

    @Override
    public Field<String> field4() {
        return Joboffer.JOBOFFER.TITLE;
    }

    @Override
    public Field<String> field5() {
        return Joboffer.JOBOFFER.DESCRIPTION;
    }

    @Override
    public Field<Integer> field6() {
        return Joboffer.JOBOFFER.ISDELETED;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Joboffer.JOBOFFER.STARTTIME;
    }

    @Override
    public Field<String> field8() {
        return Joboffer.JOBOFFER.CITY;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Joboffer.JOBOFFER.ENDTIME;
    }

    @Override
    public Field<Integer> field10() {
        return Joboffer.JOBOFFER.POSITION;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCompany();
    }

    @Override
    public Integer component3() {
        return getProfessiontype();
    }

    @Override
    public String component4() {
        return getTitle();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public Integer component6() {
        return getIsdeleted();
    }

    @Override
    public LocalDateTime component7() {
        return getStarttime();
    }

    @Override
    public String component8() {
        return getCity();
    }

    @Override
    public LocalDateTime component9() {
        return getEndtime();
    }

    @Override
    public Integer component10() {
        return getPosition();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCompany();
    }

    @Override
    public Integer value3() {
        return getProfessiontype();
    }

    @Override
    public String value4() {
        return getTitle();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public Integer value6() {
        return getIsdeleted();
    }

    @Override
    public LocalDateTime value7() {
        return getStarttime();
    }

    @Override
    public String value8() {
        return getCity();
    }

    @Override
    public LocalDateTime value9() {
        return getEndtime();
    }

    @Override
    public Integer value10() {
        return getPosition();
    }

    @Override
    public JobofferRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public JobofferRecord value2(String value) {
        setCompany(value);
        return this;
    }

    @Override
    public JobofferRecord value3(Integer value) {
        setProfessiontype(value);
        return this;
    }

    @Override
    public JobofferRecord value4(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public JobofferRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public JobofferRecord value6(Integer value) {
        setIsdeleted(value);
        return this;
    }

    @Override
    public JobofferRecord value7(LocalDateTime value) {
        setStarttime(value);
        return this;
    }

    @Override
    public JobofferRecord value8(String value) {
        setCity(value);
        return this;
    }

    @Override
    public JobofferRecord value9(LocalDateTime value) {
        setEndtime(value);
        return this;
    }

    @Override
    public JobofferRecord value10(Integer value) {
        setPosition(value);
        return this;
    }

    @Override
    public JobofferRecord values(Integer value1, String value2, Integer value3, String value4, String value5, Integer value6, LocalDateTime value7, String value8, LocalDateTime value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IJoboffer from) {
        setId(from.getId());
        setCompany(from.getCompany());
        setProfessiontype(from.getProfessiontype());
        setTitle(from.getTitle());
        setDescription(from.getDescription());
        setIsdeleted(from.getIsdeleted());
        setStarttime(from.getStarttime());
        setCity(from.getCity());
        setEndtime(from.getEndtime());
        setPosition(from.getPosition());
    }

    @Override
    public <E extends IJoboffer> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobofferRecord
     */
    public JobofferRecord() {
        super(Joboffer.JOBOFFER);
    }

    /**
     * Create a detached, initialised JobofferRecord
     */
    public JobofferRecord(Integer id, String company, Integer professiontype, String title, String description, Integer isdeleted, LocalDateTime starttime, String city, LocalDateTime endtime, Integer position) {
        super(Joboffer.JOBOFFER);

        set(0, id);
        set(1, company);
        set(2, professiontype);
        set(3, title);
        set(4, description);
        set(5, isdeleted);
        set(6, starttime);
        set(7, city);
        set(8, endtime);
        set(9, position);
    }
}
