/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.records;


import com.doteadore.recruitment_backend.codegen.tables.Resume;
import com.doteadore.recruitment_backend.codegen.tables.interfaces.IResume;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResumeRecord extends UpdatableRecordImpl<ResumeRecord> implements Record16<Integer, String, Integer, String, Integer, String, Integer, String, String, String, String, String, String, Integer, LocalDateTime, LocalDateTime>, IResume {

    private static final long serialVersionUID = -111127735;

    /**
     * Setter for <code>Recruitment.Resume.id</code>.
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Recruitment.Resume.id</code>.
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Recruitment.Resume.userid</code>. 外键（对应UserAccount:account)
     */
    @Override
    public void setUserid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Recruitment.Resume.userid</code>. 外键（对应UserAccount:account)
     */
    @Override
    public String getUserid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Recruitment.Resume.jobId</code>. 外键对应（JobOffer：id)
     */
    @Override
    public void setJobid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Recruitment.Resume.jobId</code>. 外键对应（JobOffer：id)
     */
    @Override
    public Integer getJobid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>Recruitment.Resume.name</code>. 真实姓名
     */
    @Override
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Recruitment.Resume.name</code>. 真实姓名
     */
    @Override
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>Recruitment.Resume.sex</code>. 性别
     */
    @Override
    public void setSex(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>Recruitment.Resume.sex</code>. 性别
     */
    @Override
    public Integer getSex() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>Recruitment.Resume.school</code>. 毕业学校
     */
    @Override
    public void setSchool(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>Recruitment.Resume.school</code>. 毕业学校
     */
    @Override
    public String getSchool() {
        return (String) get(5);
    }

    /**
     * Setter for <code>Recruitment.Resume.graduationYear</code>. 毕业年份
     */
    @Override
    public void setGraduationyear(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>Recruitment.Resume.graduationYear</code>. 毕业年份
     */
    @Override
    public Integer getGraduationyear() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>Recruitment.Resume.education</code>. 最高学历
     */
    @Override
    public void setEducation(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>Recruitment.Resume.education</code>. 最高学历
     */
    @Override
    public String getEducation() {
        return (String) get(7);
    }

    /**
     * Setter for <code>Recruitment.Resume.city</code>. 所在城市
     */
    @Override
    public void setCity(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>Recruitment.Resume.city</code>. 所在城市
     */
    @Override
    public String getCity() {
        return (String) get(8);
    }

    /**
     * Setter for <code>Recruitment.Resume.tele</code>. 电话
     */
    @Override
    public void setTele(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>Recruitment.Resume.tele</code>. 电话
     */
    @Override
    public String getTele() {
        return (String) get(9);
    }

    /**
     * Setter for <code>Recruitment.Resume.email</code>. 邮箱
     */
    @Override
    public void setEmail(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>Recruitment.Resume.email</code>. 邮箱
     */
    @Override
    public String getEmail() {
        return (String) get(10);
    }

    /**
     * Setter for <code>Recruitment.Resume.attatchmentUrl</code>. 可下载的简历附件
     */
    @Override
    public void setAttatchmenturl(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>Recruitment.Resume.attatchmentUrl</code>. 可下载的简历附件
     */
    @Override
    public String getAttatchmenturl() {
        return (String) get(11);
    }

    /**
     * Setter for <code>Recruitment.Resume.state</code>. 状态
     */
    @Override
    public void setState(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>Recruitment.Resume.state</code>. 状态
     */
    @Override
    public String getState() {
        return (String) get(12);
    }

    /**
     * Setter for <code>Recruitment.Resume.isPassed</code>. 0表示未通过，1表示通过，2表示还没结果
     */
    @Override
    public void setIspassed(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>Recruitment.Resume.isPassed</code>. 0表示未通过，1表示通过，2表示还没结果
     */
    @Override
    public Integer getIspassed() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>Recruitment.Resume.stateTime</code>. 状态更新时间
     */
    @Override
    public void setStatetime(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>Recruitment.Resume.stateTime</code>. 状态更新时间
     */
    @Override
    public LocalDateTime getStatetime() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>Recruitment.Resume.postTime</code>. 投递时间
     */
    @Override
    public void setPosttime(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>Recruitment.Resume.postTime</code>. 投递时间
     */
    @Override
    public LocalDateTime getPosttime() {
        return (LocalDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Integer, String, Integer, String, Integer, String, Integer, String, String, String, String, String, String, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Integer, String, Integer, String, Integer, String, Integer, String, String, String, String, String, String, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Resume.RESUME.ID;
    }

    @Override
    public Field<String> field2() {
        return Resume.RESUME.USERID;
    }

    @Override
    public Field<Integer> field3() {
        return Resume.RESUME.JOBID;
    }

    @Override
    public Field<String> field4() {
        return Resume.RESUME.NAME;
    }

    @Override
    public Field<Integer> field5() {
        return Resume.RESUME.SEX;
    }

    @Override
    public Field<String> field6() {
        return Resume.RESUME.SCHOOL;
    }

    @Override
    public Field<Integer> field7() {
        return Resume.RESUME.GRADUATIONYEAR;
    }

    @Override
    public Field<String> field8() {
        return Resume.RESUME.EDUCATION;
    }

    @Override
    public Field<String> field9() {
        return Resume.RESUME.CITY;
    }

    @Override
    public Field<String> field10() {
        return Resume.RESUME.TELE;
    }

    @Override
    public Field<String> field11() {
        return Resume.RESUME.EMAIL;
    }

    @Override
    public Field<String> field12() {
        return Resume.RESUME.ATTATCHMENTURL;
    }

    @Override
    public Field<String> field13() {
        return Resume.RESUME.STATE;
    }

    @Override
    public Field<Integer> field14() {
        return Resume.RESUME.ISPASSED;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return Resume.RESUME.STATETIME;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return Resume.RESUME.POSTTIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUserid();
    }

    @Override
    public Integer component3() {
        return getJobid();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public Integer component5() {
        return getSex();
    }

    @Override
    public String component6() {
        return getSchool();
    }

    @Override
    public Integer component7() {
        return getGraduationyear();
    }

    @Override
    public String component8() {
        return getEducation();
    }

    @Override
    public String component9() {
        return getCity();
    }

    @Override
    public String component10() {
        return getTele();
    }

    @Override
    public String component11() {
        return getEmail();
    }

    @Override
    public String component12() {
        return getAttatchmenturl();
    }

    @Override
    public String component13() {
        return getState();
    }

    @Override
    public Integer component14() {
        return getIspassed();
    }

    @Override
    public LocalDateTime component15() {
        return getStatetime();
    }

    @Override
    public LocalDateTime component16() {
        return getPosttime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUserid();
    }

    @Override
    public Integer value3() {
        return getJobid();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public Integer value5() {
        return getSex();
    }

    @Override
    public String value6() {
        return getSchool();
    }

    @Override
    public Integer value7() {
        return getGraduationyear();
    }

    @Override
    public String value8() {
        return getEducation();
    }

    @Override
    public String value9() {
        return getCity();
    }

    @Override
    public String value10() {
        return getTele();
    }

    @Override
    public String value11() {
        return getEmail();
    }

    @Override
    public String value12() {
        return getAttatchmenturl();
    }

    @Override
    public String value13() {
        return getState();
    }

    @Override
    public Integer value14() {
        return getIspassed();
    }

    @Override
    public LocalDateTime value15() {
        return getStatetime();
    }

    @Override
    public LocalDateTime value16() {
        return getPosttime();
    }

    @Override
    public ResumeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ResumeRecord value2(String value) {
        setUserid(value);
        return this;
    }

    @Override
    public ResumeRecord value3(Integer value) {
        setJobid(value);
        return this;
    }

    @Override
    public ResumeRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public ResumeRecord value5(Integer value) {
        setSex(value);
        return this;
    }

    @Override
    public ResumeRecord value6(String value) {
        setSchool(value);
        return this;
    }

    @Override
    public ResumeRecord value7(Integer value) {
        setGraduationyear(value);
        return this;
    }

    @Override
    public ResumeRecord value8(String value) {
        setEducation(value);
        return this;
    }

    @Override
    public ResumeRecord value9(String value) {
        setCity(value);
        return this;
    }

    @Override
    public ResumeRecord value10(String value) {
        setTele(value);
        return this;
    }

    @Override
    public ResumeRecord value11(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public ResumeRecord value12(String value) {
        setAttatchmenturl(value);
        return this;
    }

    @Override
    public ResumeRecord value13(String value) {
        setState(value);
        return this;
    }

    @Override
    public ResumeRecord value14(Integer value) {
        setIspassed(value);
        return this;
    }

    @Override
    public ResumeRecord value15(LocalDateTime value) {
        setStatetime(value);
        return this;
    }

    @Override
    public ResumeRecord value16(LocalDateTime value) {
        setPosttime(value);
        return this;
    }

    @Override
    public ResumeRecord values(Integer value1, String value2, Integer value3, String value4, Integer value5, String value6, Integer value7, String value8, String value9, String value10, String value11, String value12, String value13, Integer value14, LocalDateTime value15, LocalDateTime value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IResume from) {
        setId(from.getId());
        setUserid(from.getUserid());
        setJobid(from.getJobid());
        setName(from.getName());
        setSex(from.getSex());
        setSchool(from.getSchool());
        setGraduationyear(from.getGraduationyear());
        setEducation(from.getEducation());
        setCity(from.getCity());
        setTele(from.getTele());
        setEmail(from.getEmail());
        setAttatchmenturl(from.getAttatchmenturl());
        setState(from.getState());
        setIspassed(from.getIspassed());
        setStatetime(from.getStatetime());
        setPosttime(from.getPosttime());
    }

    @Override
    public <E extends IResume> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResumeRecord
     */
    public ResumeRecord() {
        super(Resume.RESUME);
    }

    /**
     * Create a detached, initialised ResumeRecord
     */
    public ResumeRecord(Integer id, String userid, Integer jobid, String name, Integer sex, String school, Integer graduationyear, String education, String city, String tele, String email, String attatchmenturl, String state, Integer ispassed, LocalDateTime statetime, LocalDateTime posttime) {
        super(Resume.RESUME);

        set(0, id);
        set(1, userid);
        set(2, jobid);
        set(3, name);
        set(4, sex);
        set(5, school);
        set(6, graduationyear);
        set(7, education);
        set(8, city);
        set(9, tele);
        set(10, email);
        set(11, attatchmenturl);
        set(12, state);
        set(13, ispassed);
        set(14, statetime);
        set(15, posttime);
    }
}
