/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables;


import com.doteadore.recruitment_backend.codegen.Keys;
import com.doteadore.recruitment_backend.codegen.Recruitment;
import com.doteadore.recruitment_backend.codegen.tables.records.EducationRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Education extends TableImpl<EducationRecord> {

    private static final long serialVersionUID = 1541993925;

    /**
     * The reference instance of <code>Recruitment.Education</code>
     */
    public static final Education EDUCATION = new Education();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EducationRecord> getRecordType() {
        return EducationRecord.class;
    }

    /**
     * The column <code>Recruitment.Education.key</code>.
     */
    public final TableField<EducationRecord, Integer> KEY = createField(DSL.name("key"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>Recruitment.Education.value</code>.
     */
    public final TableField<EducationRecord, String> VALUE = createField(DSL.name("value"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>Recruitment.Education</code> table reference
     */
    public Education() {
        this(DSL.name("Education"), null);
    }

    /**
     * Create an aliased <code>Recruitment.Education</code> table reference
     */
    public Education(String alias) {
        this(DSL.name(alias), EDUCATION);
    }

    /**
     * Create an aliased <code>Recruitment.Education</code> table reference
     */
    public Education(Name alias) {
        this(alias, EDUCATION);
    }

    private Education(Name alias, Table<EducationRecord> aliased) {
        this(alias, aliased, null);
    }

    private Education(Name alias, Table<EducationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Education(Table<O> child, ForeignKey<O, EducationRecord> key) {
        super(child, key, EDUCATION);
    }

    @Override
    public Schema getSchema() {
        return Recruitment.RECRUITMENT;
    }

    @Override
    public Identity<EducationRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EDUCATION;
    }

    @Override
    public UniqueKey<EducationRecord> getPrimaryKey() {
        return Keys.KEY_EDUCATION_PRIMARY;
    }

    @Override
    public List<UniqueKey<EducationRecord>> getKeys() {
        return Arrays.<UniqueKey<EducationRecord>>asList(Keys.KEY_EDUCATION_PRIMARY);
    }

    @Override
    public Education as(String alias) {
        return new Education(DSL.name(alias), this);
    }

    @Override
    public Education as(Name alias) {
        return new Education(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Education rename(String name) {
        return new Education(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Education rename(Name name) {
        return new Education(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
