/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables;


import com.doteadore.recruitment_backend.codegen.Keys;
import com.doteadore.recruitment_backend.codegen.Recruitment;
import com.doteadore.recruitment_backend.codegen.tables.records.ProfessionpositionRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Professionposition extends TableImpl<ProfessionpositionRecord> {

    private static final long serialVersionUID = -1160148017;

    /**
     * The reference instance of <code>Recruitment.ProfessionPosition</code>
     */
    public static final Professionposition PROFESSIONPOSITION = new Professionposition();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProfessionpositionRecord> getRecordType() {
        return ProfessionpositionRecord.class;
    }

    /**
     * The column <code>Recruitment.ProfessionPosition.key</code>.
     */
    public final TableField<ProfessionpositionRecord, Integer> KEY = createField(DSL.name("key"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>Recruitment.ProfessionPosition.value</code>.
     */
    public final TableField<ProfessionpositionRecord, String> VALUE = createField(DSL.name("value"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>Recruitment.ProfessionPosition</code> table reference
     */
    public Professionposition() {
        this(DSL.name("ProfessionPosition"), null);
    }

    /**
     * Create an aliased <code>Recruitment.ProfessionPosition</code> table reference
     */
    public Professionposition(String alias) {
        this(DSL.name(alias), PROFESSIONPOSITION);
    }

    /**
     * Create an aliased <code>Recruitment.ProfessionPosition</code> table reference
     */
    public Professionposition(Name alias) {
        this(alias, PROFESSIONPOSITION);
    }

    private Professionposition(Name alias, Table<ProfessionpositionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Professionposition(Name alias, Table<ProfessionpositionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Professionposition(Table<O> child, ForeignKey<O, ProfessionpositionRecord> key) {
        super(child, key, PROFESSIONPOSITION);
    }

    @Override
    public Schema getSchema() {
        return Recruitment.RECRUITMENT;
    }

    @Override
    public Identity<ProfessionpositionRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PROFESSIONPOSITION;
    }

    @Override
    public UniqueKey<ProfessionpositionRecord> getPrimaryKey() {
        return Keys.KEY_PROFESSIONPOSITION_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProfessionpositionRecord>> getKeys() {
        return Arrays.<UniqueKey<ProfessionpositionRecord>>asList(Keys.KEY_PROFESSIONPOSITION_PRIMARY);
    }

    @Override
    public Professionposition as(String alias) {
        return new Professionposition(DSL.name(alias), this);
    }

    @Override
    public Professionposition as(Name alias) {
        return new Professionposition(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Professionposition rename(String name) {
        return new Professionposition(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Professionposition rename(Name name) {
        return new Professionposition(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
