/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables;


import com.doteadore.recruitment_backend.codegen.Keys;
import com.doteadore.recruitment_backend.codegen.Recruitment;
import com.doteadore.recruitment_backend.codegen.tables.records.ProfessiontypeRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Professiontype extends TableImpl<ProfessiontypeRecord> {

    private static final long serialVersionUID = -2010385265;

    /**
     * The reference instance of <code>Recruitment.ProfessionType</code>
     */
    public static final Professiontype PROFESSIONTYPE = new Professiontype();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProfessiontypeRecord> getRecordType() {
        return ProfessiontypeRecord.class;
    }

    /**
     * The column <code>Recruitment.ProfessionType.key</code>.
     */
    public final TableField<ProfessiontypeRecord, Integer> KEY = createField(DSL.name("key"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>Recruitment.ProfessionType.value</code>.
     */
    public final TableField<ProfessiontypeRecord, String> VALUE = createField(DSL.name("value"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>Recruitment.ProfessionType</code> table reference
     */
    public Professiontype() {
        this(DSL.name("ProfessionType"), null);
    }

    /**
     * Create an aliased <code>Recruitment.ProfessionType</code> table reference
     */
    public Professiontype(String alias) {
        this(DSL.name(alias), PROFESSIONTYPE);
    }

    /**
     * Create an aliased <code>Recruitment.ProfessionType</code> table reference
     */
    public Professiontype(Name alias) {
        this(alias, PROFESSIONTYPE);
    }

    private Professiontype(Name alias, Table<ProfessiontypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Professiontype(Name alias, Table<ProfessiontypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Professiontype(Table<O> child, ForeignKey<O, ProfessiontypeRecord> key) {
        super(child, key, PROFESSIONTYPE);
    }

    @Override
    public Schema getSchema() {
        return Recruitment.RECRUITMENT;
    }

    @Override
    public Identity<ProfessiontypeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PROFESSIONTYPE;
    }

    @Override
    public UniqueKey<ProfessiontypeRecord> getPrimaryKey() {
        return Keys.KEY_PROFESSIONTYPE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProfessiontypeRecord>> getKeys() {
        return Arrays.<UniqueKey<ProfessiontypeRecord>>asList(Keys.KEY_PROFESSIONTYPE_PRIMARY);
    }

    @Override
    public Professiontype as(String alias) {
        return new Professiontype(DSL.name(alias), this);
    }

    @Override
    public Professiontype as(Name alias) {
        return new Professiontype(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Professiontype rename(String name) {
        return new Professiontype(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Professiontype rename(Name name) {
        return new Professiontype(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
