/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.daos;


import com.doteadore.recruitment_backend.codegen.tables.Homepushapplication;
import com.doteadore.recruitment_backend.codegen.tables.records.HomepushapplicationRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HomepushapplicationDao extends DAOImpl<HomepushapplicationRecord, com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication, Integer> {

    /**
     * Create a new HomepushapplicationDao without any configuration
     */
    public HomepushapplicationDao() {
        super(Homepushapplication.HOMEPUSHAPPLICATION, com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication.class);
    }

    /**
     * Create a new HomepushapplicationDao with an attached configuration
     */
    public HomepushapplicationDao(Configuration configuration) {
        super(Homepushapplication.HOMEPUSHAPPLICATION, com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication.class, configuration);
    }

    @Override
    public Integer getId(com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Homepushapplication.HOMEPUSHAPPLICATION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchById(Integer... values) {
        return fetch(Homepushapplication.HOMEPUSHAPPLICATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication fetchOneById(Integer value) {
        return fetchOne(Homepushapplication.HOMEPUSHAPPLICATION.ID, value);
    }

    /**
     * Fetch records that have <code>companyId BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchRangeOfCompanyid(String lowerInclusive, String upperInclusive) {
        return fetchRange(Homepushapplication.HOMEPUSHAPPLICATION.COMPANYID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>companyId IN (values)</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchByCompanyid(String... values) {
        return fetch(Homepushapplication.HOMEPUSHAPPLICATION.COMPANYID, values);
    }

    /**
     * Fetch records that have <code>endtime BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchRangeOfEndtime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Homepushapplication.HOMEPUSHAPPLICATION.ENDTIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>endtime IN (values)</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchByEndtime(LocalDateTime... values) {
        return fetch(Homepushapplication.HOMEPUSHAPPLICATION.ENDTIME, values);
    }

    /**
     * Fetch records that have <code>handleAdminId BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchRangeOfHandleadminid(String lowerInclusive, String upperInclusive) {
        return fetchRange(Homepushapplication.HOMEPUSHAPPLICATION.HANDLEADMINID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>handleAdminId IN (values)</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchByHandleadminid(String... values) {
        return fetch(Homepushapplication.HOMEPUSHAPPLICATION.HANDLEADMINID, values);
    }

    /**
     * Fetch records that have <code>handleTime BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchRangeOfHandletime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Homepushapplication.HOMEPUSHAPPLICATION.HANDLETIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>handleTime IN (values)</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchByHandletime(LocalDateTime... values) {
        return fetch(Homepushapplication.HOMEPUSHAPPLICATION.HANDLETIME, values);
    }

    /**
     * Fetch records that have <code>handleRes BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchRangeOfHandleres(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Homepushapplication.HOMEPUSHAPPLICATION.HANDLERES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>handleRes IN (values)</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchByHandleres(Integer... values) {
        return fetch(Homepushapplication.HOMEPUSHAPPLICATION.HANDLERES, values);
    }

    /**
     * Fetch records that have <code>handleResponseContent BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchRangeOfHandleresponsecontent(String lowerInclusive, String upperInclusive) {
        return fetchRange(Homepushapplication.HOMEPUSHAPPLICATION.HANDLERESPONSECONTENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>handleResponseContent IN (values)</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchByHandleresponsecontent(String... values) {
        return fetch(Homepushapplication.HOMEPUSHAPPLICATION.HANDLERESPONSECONTENT, values);
    }

    /**
     * Fetch records that have <code>hasReadByCompany BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchRangeOfHasreadbycompany(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Homepushapplication.HOMEPUSHAPPLICATION.HASREADBYCOMPANY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>hasReadByCompany IN (values)</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchByHasreadbycompany(Integer... values) {
        return fetch(Homepushapplication.HOMEPUSHAPPLICATION.HASREADBYCOMPANY, values);
    }

    /**
     * Fetch records that have <code>jobOfferId BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchRangeOfJobofferid(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Homepushapplication.HOMEPUSHAPPLICATION.JOBOFFERID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>jobOfferId IN (values)</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Homepushapplication> fetchByJobofferid(Integer... values) {
        return fetch(Homepushapplication.HOMEPUSHAPPLICATION.JOBOFFERID, values);
    }
}
