/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.daos;


import com.doteadore.recruitment_backend.codegen.tables.Professiontype;
import com.doteadore.recruitment_backend.codegen.tables.records.ProfessiontypeRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ProfessiontypeDao extends DAOImpl<ProfessiontypeRecord, com.doteadore.recruitment_backend.codegen.tables.pojos.Professiontype, Integer> {

    /**
     * Create a new ProfessiontypeDao without any configuration
     */
    public ProfessiontypeDao() {
        super(Professiontype.PROFESSIONTYPE, com.doteadore.recruitment_backend.codegen.tables.pojos.Professiontype.class);
    }

    /**
     * Create a new ProfessiontypeDao with an attached configuration
     */
    @Autowired
    public ProfessiontypeDao(Configuration configuration) {
        super(Professiontype.PROFESSIONTYPE, com.doteadore.recruitment_backend.codegen.tables.pojos.Professiontype.class, configuration);
    }

    @Override
    public Integer getId(com.doteadore.recruitment_backend.codegen.tables.pojos.Professiontype object) {
        return object.getKey();
    }

    /**
     * Fetch records that have <code>key BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Professiontype> fetchRangeOfKey(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Professiontype.PROFESSIONTYPE.KEY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>key IN (values)</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Professiontype> fetchByKey(Integer... values) {
        return fetch(Professiontype.PROFESSIONTYPE.KEY, values);
    }

    /**
     * Fetch a unique record that has <code>key = value</code>
     */
    public com.doteadore.recruitment_backend.codegen.tables.pojos.Professiontype fetchOneByKey(Integer value) {
        return fetchOne(Professiontype.PROFESSIONTYPE.KEY, value);
    }

    /**
     * Fetch records that have <code>value BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Professiontype> fetchRangeOfValue(String lowerInclusive, String upperInclusive) {
        return fetchRange(Professiontype.PROFESSIONTYPE.VALUE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>value IN (values)</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Professiontype> fetchByValue(String... values) {
        return fetch(Professiontype.PROFESSIONTYPE.VALUE, values);
    }
}
