/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen.tables.daos;


import com.doteadore.recruitment_backend.codegen.tables.Resumestate;
import com.doteadore.recruitment_backend.codegen.tables.records.ResumestateRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResumestateDao extends DAOImpl<ResumestateRecord, com.doteadore.recruitment_backend.codegen.tables.pojos.Resumestate, Integer> {

    /**
     * Create a new ResumestateDao without any configuration
     */
    public ResumestateDao() {
        super(Resumestate.RESUMESTATE, com.doteadore.recruitment_backend.codegen.tables.pojos.Resumestate.class);
    }

    /**
     * Create a new ResumestateDao with an attached configuration
     */
    public ResumestateDao(Configuration configuration) {
        super(Resumestate.RESUMESTATE, com.doteadore.recruitment_backend.codegen.tables.pojos.Resumestate.class, configuration);
    }

    @Override
    public Integer getId(com.doteadore.recruitment_backend.codegen.tables.pojos.Resumestate object) {
        return object.getKey();
    }

    /**
     * Fetch records that have <code>key BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Resumestate> fetchRangeOfKey(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Resumestate.RESUMESTATE.KEY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>key IN (values)</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Resumestate> fetchByKey(Integer... values) {
        return fetch(Resumestate.RESUMESTATE.KEY, values);
    }

    /**
     * Fetch a unique record that has <code>key = value</code>
     */
    public com.doteadore.recruitment_backend.codegen.tables.pojos.Resumestate fetchOneByKey(Integer value) {
        return fetchOne(Resumestate.RESUMESTATE.KEY, value);
    }

    /**
     * Fetch records that have <code>value BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Resumestate> fetchRangeOfValue(String lowerInclusive, String upperInclusive) {
        return fetchRange(Resumestate.RESUMESTATE.VALUE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>value IN (values)</code>
     */
    public List<com.doteadore.recruitment_backend.codegen.tables.pojos.Resumestate> fetchByValue(String... values) {
        return fetch(Resumestate.RESUMESTATE.VALUE, values);
    }
}
