/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen;


import com.doteadore.recruitment_backend.codegen.tables.Comment;
import com.doteadore.recruitment_backend.codegen.tables.Homepush;
import com.doteadore.recruitment_backend.codegen.tables.Homepushapplication;
import com.doteadore.recruitment_backend.codegen.tables.Joboffer;
import com.doteadore.recruitment_backend.codegen.tables.Resume;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>Recruitment</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COMMENT_COMMENT_FK1 = Indexes0.COMMENT_COMMENT_FK1;
    public static final Index COMMENT_COMMENT_FK2 = Indexes0.COMMENT_COMMENT_FK2;
    public static final Index COMMENT_COMMENT_FK3 = Indexes0.COMMENT_COMMENT_FK3;
    public static final Index HOMEPUSH_HOMEPUSH_FK1 = Indexes0.HOMEPUSH_HOMEPUSH_FK1;
    public static final Index HOMEPUSH_HOMEPUSH_FK2 = Indexes0.HOMEPUSH_HOMEPUSH_FK2;
    public static final Index HOMEPUSHAPPLICATION_HOMEPUSHAPPLICATION_FK1 = Indexes0.HOMEPUSHAPPLICATION_HOMEPUSHAPPLICATION_FK1;
    public static final Index HOMEPUSHAPPLICATION_HOMEPUSHAPPLICATION_FK2 = Indexes0.HOMEPUSHAPPLICATION_HOMEPUSHAPPLICATION_FK2;
    public static final Index HOMEPUSHAPPLICATION_HOMEPUSHAPPLICATION_FK3 = Indexes0.HOMEPUSHAPPLICATION_HOMEPUSHAPPLICATION_FK3;
    public static final Index JOBOFFER_JOBOFFER_FK1 = Indexes0.JOBOFFER_JOBOFFER_FK1;
    public static final Index JOBOFFER_JONOFFER_FK2 = Indexes0.JOBOFFER_JONOFFER_FK2;
    public static final Index JOBOFFER_POSITION = Indexes0.JOBOFFER_POSITION;
    public static final Index RESUME_RESUME_FK1 = Indexes0.RESUME_RESUME_FK1;
    public static final Index RESUME_RESUME_FK2 = Indexes0.RESUME_RESUME_FK2;
    public static final Index RESUME_RESUME_FK3 = Indexes0.RESUME_RESUME_FK3;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index COMMENT_COMMENT_FK1 = Internal.createIndex("Comment_fk1", Comment.COMMENT, new OrderField[] { Comment.COMMENT.JOBOFFERID }, false);
        public static Index COMMENT_COMMENT_FK2 = Internal.createIndex("Comment_fk2", Comment.COMMENT, new OrderField[] { Comment.COMMENT.ACCOUNTID }, false);
        public static Index COMMENT_COMMENT_FK3 = Internal.createIndex("Comment_fk3", Comment.COMMENT, new OrderField[] { Comment.COMMENT.RESPONSEID }, false);
        public static Index HOMEPUSH_HOMEPUSH_FK1 = Internal.createIndex("HomePush_fk1", Homepush.HOMEPUSH, new OrderField[] { Homepush.HOMEPUSH.JOBOFFER }, false);
        public static Index HOMEPUSH_HOMEPUSH_FK2 = Internal.createIndex("HomePush_fk2", Homepush.HOMEPUSH, new OrderField[] { Homepush.HOMEPUSH.HANDLEADMINID }, false);
        public static Index HOMEPUSHAPPLICATION_HOMEPUSHAPPLICATION_FK1 = Internal.createIndex("HomePushApplication_fk1", Homepushapplication.HOMEPUSHAPPLICATION, new OrderField[] { Homepushapplication.HOMEPUSHAPPLICATION.COMPANYID }, false);
        public static Index HOMEPUSHAPPLICATION_HOMEPUSHAPPLICATION_FK2 = Internal.createIndex("HomePushApplication_fk2", Homepushapplication.HOMEPUSHAPPLICATION, new OrderField[] { Homepushapplication.HOMEPUSHAPPLICATION.JOBOFFERID }, false);
        public static Index HOMEPUSHAPPLICATION_HOMEPUSHAPPLICATION_FK3 = Internal.createIndex("HomePushApplication_fk3", Homepushapplication.HOMEPUSHAPPLICATION, new OrderField[] { Homepushapplication.HOMEPUSHAPPLICATION.HANDLEADMINID }, false);
        public static Index JOBOFFER_JOBOFFER_FK1 = Internal.createIndex("JobOffer_fk1", Joboffer.JOBOFFER, new OrderField[] { Joboffer.JOBOFFER.COMPANY }, false);
        public static Index JOBOFFER_JONOFFER_FK2 = Internal.createIndex("JonOffer_fk2", Joboffer.JOBOFFER, new OrderField[] { Joboffer.JOBOFFER.PROFESSIONTYPE }, false);
        public static Index JOBOFFER_POSITION = Internal.createIndex("position", Joboffer.JOBOFFER, new OrderField[] { Joboffer.JOBOFFER.POSITION }, false);
        public static Index RESUME_RESUME_FK1 = Internal.createIndex("Resume_fk1", Resume.RESUME, new OrderField[] { Resume.RESUME.USERID }, false);
        public static Index RESUME_RESUME_FK2 = Internal.createIndex("Resume_fk2", Resume.RESUME, new OrderField[] { Resume.RESUME.JOBID }, false);
        public static Index RESUME_RESUME_FK3 = Internal.createIndex("Resume_fk3", Resume.RESUME, new OrderField[] { Resume.RESUME.EDUCATION }, false);
    }
}
