/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen;


import com.doteadore.recruitment_backend.codegen.tables.Adminaccount;
import com.doteadore.recruitment_backend.codegen.tables.Comment;
import com.doteadore.recruitment_backend.codegen.tables.Companyaccount;
import com.doteadore.recruitment_backend.codegen.tables.Education;
import com.doteadore.recruitment_backend.codegen.tables.Homepush;
import com.doteadore.recruitment_backend.codegen.tables.Homepushapplication;
import com.doteadore.recruitment_backend.codegen.tables.Joboffer;
import com.doteadore.recruitment_backend.codegen.tables.Professionposition;
import com.doteadore.recruitment_backend.codegen.tables.Professiontype;
import com.doteadore.recruitment_backend.codegen.tables.Resume;
import com.doteadore.recruitment_backend.codegen.tables.Resumestate;
import com.doteadore.recruitment_backend.codegen.tables.Useraccont;
import com.doteadore.recruitment_backend.codegen.tables.Userdetailinfo;
import com.doteadore.recruitment_backend.codegen.tables.records.AdminaccountRecord;
import com.doteadore.recruitment_backend.codegen.tables.records.CommentRecord;
import com.doteadore.recruitment_backend.codegen.tables.records.CompanyaccountRecord;
import com.doteadore.recruitment_backend.codegen.tables.records.EducationRecord;
import com.doteadore.recruitment_backend.codegen.tables.records.HomepushRecord;
import com.doteadore.recruitment_backend.codegen.tables.records.HomepushapplicationRecord;
import com.doteadore.recruitment_backend.codegen.tables.records.JobofferRecord;
import com.doteadore.recruitment_backend.codegen.tables.records.ProfessionpositionRecord;
import com.doteadore.recruitment_backend.codegen.tables.records.ProfessiontypeRecord;
import com.doteadore.recruitment_backend.codegen.tables.records.ResumeRecord;
import com.doteadore.recruitment_backend.codegen.tables.records.ResumestateRecord;
import com.doteadore.recruitment_backend.codegen.tables.records.UseraccontRecord;
import com.doteadore.recruitment_backend.codegen.tables.records.UserdetailinfoRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>Recruitment</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CommentRecord, Integer> IDENTITY_COMMENT = Identities0.IDENTITY_COMMENT;
    public static final Identity<EducationRecord, Integer> IDENTITY_EDUCATION = Identities0.IDENTITY_EDUCATION;
    public static final Identity<HomepushRecord, Integer> IDENTITY_HOMEPUSH = Identities0.IDENTITY_HOMEPUSH;
    public static final Identity<HomepushapplicationRecord, Integer> IDENTITY_HOMEPUSHAPPLICATION = Identities0.IDENTITY_HOMEPUSHAPPLICATION;
    public static final Identity<JobofferRecord, Integer> IDENTITY_JOBOFFER = Identities0.IDENTITY_JOBOFFER;
    public static final Identity<ProfessionpositionRecord, Integer> IDENTITY_PROFESSIONPOSITION = Identities0.IDENTITY_PROFESSIONPOSITION;
    public static final Identity<ProfessiontypeRecord, Integer> IDENTITY_PROFESSIONTYPE = Identities0.IDENTITY_PROFESSIONTYPE;
    public static final Identity<ResumeRecord, Integer> IDENTITY_RESUME = Identities0.IDENTITY_RESUME;
    public static final Identity<ResumestateRecord, Integer> IDENTITY_RESUMESTATE = Identities0.IDENTITY_RESUMESTATE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AdminaccountRecord> KEY_ADMINACCOUNT_PRIMARY = UniqueKeys0.KEY_ADMINACCOUNT_PRIMARY;
    public static final UniqueKey<CommentRecord> KEY_COMMENT_PRIMARY = UniqueKeys0.KEY_COMMENT_PRIMARY;
    public static final UniqueKey<CompanyaccountRecord> KEY_COMPANYACCOUNT_PRIMARY = UniqueKeys0.KEY_COMPANYACCOUNT_PRIMARY;
    public static final UniqueKey<EducationRecord> KEY_EDUCATION_PRIMARY = UniqueKeys0.KEY_EDUCATION_PRIMARY;
    public static final UniqueKey<HomepushRecord> KEY_HOMEPUSH_PRIMARY = UniqueKeys0.KEY_HOMEPUSH_PRIMARY;
    public static final UniqueKey<HomepushapplicationRecord> KEY_HOMEPUSHAPPLICATION_PRIMARY = UniqueKeys0.KEY_HOMEPUSHAPPLICATION_PRIMARY;
    public static final UniqueKey<JobofferRecord> KEY_JOBOFFER_PRIMARY = UniqueKeys0.KEY_JOBOFFER_PRIMARY;
    public static final UniqueKey<ProfessionpositionRecord> KEY_PROFESSIONPOSITION_PRIMARY = UniqueKeys0.KEY_PROFESSIONPOSITION_PRIMARY;
    public static final UniqueKey<ProfessiontypeRecord> KEY_PROFESSIONTYPE_PRIMARY = UniqueKeys0.KEY_PROFESSIONTYPE_PRIMARY;
    public static final UniqueKey<ResumeRecord> KEY_RESUME_PRIMARY = UniqueKeys0.KEY_RESUME_PRIMARY;
    public static final UniqueKey<ResumestateRecord> KEY_RESUMESTATE_PRIMARY = UniqueKeys0.KEY_RESUMESTATE_PRIMARY;
    public static final UniqueKey<UseraccontRecord> KEY_USERACCONT_PRIMARY = UniqueKeys0.KEY_USERACCONT_PRIMARY;
    public static final UniqueKey<UserdetailinfoRecord> KEY_USERDETAILINFO_PRIMARY = UniqueKeys0.KEY_USERDETAILINFO_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CommentRecord, JobofferRecord> COMMENT_FK1 = ForeignKeys0.COMMENT_FK1;
    public static final ForeignKey<CommentRecord, UseraccontRecord> COMMENT_FK2 = ForeignKeys0.COMMENT_FK2;
    public static final ForeignKey<CommentRecord, UseraccontRecord> COMMENT_FK3 = ForeignKeys0.COMMENT_FK3;
    public static final ForeignKey<HomepushRecord, JobofferRecord> HOMEPUSH_FK1 = ForeignKeys0.HOMEPUSH_FK1;
    public static final ForeignKey<HomepushRecord, AdminaccountRecord> HOMEPUSH_FK2 = ForeignKeys0.HOMEPUSH_FK2;
    public static final ForeignKey<HomepushapplicationRecord, CompanyaccountRecord> HOMEPUSHAPPLICATION_FK1 = ForeignKeys0.HOMEPUSHAPPLICATION_FK1;
    public static final ForeignKey<HomepushapplicationRecord, AdminaccountRecord> HOMEPUSHAPPLICATION_FK3 = ForeignKeys0.HOMEPUSHAPPLICATION_FK3;
    public static final ForeignKey<HomepushapplicationRecord, JobofferRecord> HOMEPUSHAPPLICATION_FK2 = ForeignKeys0.HOMEPUSHAPPLICATION_FK2;
    public static final ForeignKey<JobofferRecord, CompanyaccountRecord> JOBOFFER_FK1 = ForeignKeys0.JOBOFFER_FK1;
    public static final ForeignKey<JobofferRecord, ProfessiontypeRecord> JONOFFER_FK2 = ForeignKeys0.JONOFFER_FK2;
    public static final ForeignKey<JobofferRecord, ProfessionpositionRecord> POSITION = ForeignKeys0.POSITION;
    public static final ForeignKey<ResumeRecord, UseraccontRecord> RESUME_FK1 = ForeignKeys0.RESUME_FK1;
    public static final ForeignKey<ResumeRecord, JobofferRecord> RESUME_FK2 = ForeignKeys0.RESUME_FK2;
    public static final ForeignKey<ResumeRecord, EducationRecord> RESUME_FK3 = ForeignKeys0.RESUME_FK3;
    public static final ForeignKey<UserdetailinfoRecord, UseraccontRecord> USERDETAILINFO_FK1 = ForeignKeys0.USERDETAILINFO_FK1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CommentRecord, Integer> IDENTITY_COMMENT = Internal.createIdentity(Comment.COMMENT, Comment.COMMENT.ID);
        public static Identity<EducationRecord, Integer> IDENTITY_EDUCATION = Internal.createIdentity(Education.EDUCATION, Education.EDUCATION.KEY);
        public static Identity<HomepushRecord, Integer> IDENTITY_HOMEPUSH = Internal.createIdentity(Homepush.HOMEPUSH, Homepush.HOMEPUSH.ID);
        public static Identity<HomepushapplicationRecord, Integer> IDENTITY_HOMEPUSHAPPLICATION = Internal.createIdentity(Homepushapplication.HOMEPUSHAPPLICATION, Homepushapplication.HOMEPUSHAPPLICATION.ID);
        public static Identity<JobofferRecord, Integer> IDENTITY_JOBOFFER = Internal.createIdentity(Joboffer.JOBOFFER, Joboffer.JOBOFFER.ID);
        public static Identity<ProfessionpositionRecord, Integer> IDENTITY_PROFESSIONPOSITION = Internal.createIdentity(Professionposition.PROFESSIONPOSITION, Professionposition.PROFESSIONPOSITION.KEY);
        public static Identity<ProfessiontypeRecord, Integer> IDENTITY_PROFESSIONTYPE = Internal.createIdentity(Professiontype.PROFESSIONTYPE, Professiontype.PROFESSIONTYPE.KEY);
        public static Identity<ResumeRecord, Integer> IDENTITY_RESUME = Internal.createIdentity(Resume.RESUME, Resume.RESUME.ID);
        public static Identity<ResumestateRecord, Integer> IDENTITY_RESUMESTATE = Internal.createIdentity(Resumestate.RESUMESTATE, Resumestate.RESUMESTATE.KEY);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AdminaccountRecord> KEY_ADMINACCOUNT_PRIMARY = Internal.createUniqueKey(Adminaccount.ADMINACCOUNT, "KEY_AdminAccount_PRIMARY", new TableField[] { Adminaccount.ADMINACCOUNT.ACCOUNT }, true);
        public static final UniqueKey<CommentRecord> KEY_COMMENT_PRIMARY = Internal.createUniqueKey(Comment.COMMENT, "KEY_Comment_PRIMARY", new TableField[] { Comment.COMMENT.ID }, true);
        public static final UniqueKey<CompanyaccountRecord> KEY_COMPANYACCOUNT_PRIMARY = Internal.createUniqueKey(Companyaccount.COMPANYACCOUNT, "KEY_CompanyAccount_PRIMARY", new TableField[] { Companyaccount.COMPANYACCOUNT.ACCOUNT }, true);
        public static final UniqueKey<EducationRecord> KEY_EDUCATION_PRIMARY = Internal.createUniqueKey(Education.EDUCATION, "KEY_Education_PRIMARY", new TableField[] { Education.EDUCATION.KEY }, true);
        public static final UniqueKey<HomepushRecord> KEY_HOMEPUSH_PRIMARY = Internal.createUniqueKey(Homepush.HOMEPUSH, "KEY_HomePush_PRIMARY", new TableField[] { Homepush.HOMEPUSH.ID }, true);
        public static final UniqueKey<HomepushapplicationRecord> KEY_HOMEPUSHAPPLICATION_PRIMARY = Internal.createUniqueKey(Homepushapplication.HOMEPUSHAPPLICATION, "KEY_HomePushApplication_PRIMARY", new TableField[] { Homepushapplication.HOMEPUSHAPPLICATION.ID }, true);
        public static final UniqueKey<JobofferRecord> KEY_JOBOFFER_PRIMARY = Internal.createUniqueKey(Joboffer.JOBOFFER, "KEY_JobOffer_PRIMARY", new TableField[] { Joboffer.JOBOFFER.ID }, true);
        public static final UniqueKey<ProfessionpositionRecord> KEY_PROFESSIONPOSITION_PRIMARY = Internal.createUniqueKey(Professionposition.PROFESSIONPOSITION, "KEY_ProfessionPosition_PRIMARY", new TableField[] { Professionposition.PROFESSIONPOSITION.KEY }, true);
        public static final UniqueKey<ProfessiontypeRecord> KEY_PROFESSIONTYPE_PRIMARY = Internal.createUniqueKey(Professiontype.PROFESSIONTYPE, "KEY_ProfessionType_PRIMARY", new TableField[] { Professiontype.PROFESSIONTYPE.KEY }, true);
        public static final UniqueKey<ResumeRecord> KEY_RESUME_PRIMARY = Internal.createUniqueKey(Resume.RESUME, "KEY_Resume_PRIMARY", new TableField[] { Resume.RESUME.ID }, true);
        public static final UniqueKey<ResumestateRecord> KEY_RESUMESTATE_PRIMARY = Internal.createUniqueKey(Resumestate.RESUMESTATE, "KEY_ResumeState_PRIMARY", new TableField[] { Resumestate.RESUMESTATE.KEY }, true);
        public static final UniqueKey<UseraccontRecord> KEY_USERACCONT_PRIMARY = Internal.createUniqueKey(Useraccont.USERACCONT, "KEY_UserAccont_PRIMARY", new TableField[] { Useraccont.USERACCONT.ACCOUNT }, true);
        public static final UniqueKey<UserdetailinfoRecord> KEY_USERDETAILINFO_PRIMARY = Internal.createUniqueKey(Userdetailinfo.USERDETAILINFO, "KEY_UserDetailInfo_PRIMARY", new TableField[] { Userdetailinfo.USERDETAILINFO.ACCOUNT }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<CommentRecord, JobofferRecord> COMMENT_FK1 = Internal.createForeignKey(Keys.KEY_JOBOFFER_PRIMARY, Comment.COMMENT, "Comment_fk1", new TableField[] { Comment.COMMENT.JOBOFFERID }, true);
        public static final ForeignKey<CommentRecord, UseraccontRecord> COMMENT_FK2 = Internal.createForeignKey(Keys.KEY_USERACCONT_PRIMARY, Comment.COMMENT, "Comment_fk2", new TableField[] { Comment.COMMENT.ACCOUNTID }, true);
        public static final ForeignKey<CommentRecord, UseraccontRecord> COMMENT_FK3 = Internal.createForeignKey(Keys.KEY_USERACCONT_PRIMARY, Comment.COMMENT, "Comment_fk3", new TableField[] { Comment.COMMENT.RESPONSEID }, true);
        public static final ForeignKey<HomepushRecord, JobofferRecord> HOMEPUSH_FK1 = Internal.createForeignKey(Keys.KEY_JOBOFFER_PRIMARY, Homepush.HOMEPUSH, "HomePush_fk1", new TableField[] { Homepush.HOMEPUSH.JOBOFFER }, true);
        public static final ForeignKey<HomepushRecord, AdminaccountRecord> HOMEPUSH_FK2 = Internal.createForeignKey(Keys.KEY_ADMINACCOUNT_PRIMARY, Homepush.HOMEPUSH, "HomePush_fk2", new TableField[] { Homepush.HOMEPUSH.HANDLEADMINID }, true);
        public static final ForeignKey<HomepushapplicationRecord, CompanyaccountRecord> HOMEPUSHAPPLICATION_FK1 = Internal.createForeignKey(Keys.KEY_COMPANYACCOUNT_PRIMARY, Homepushapplication.HOMEPUSHAPPLICATION, "HomePushApplication_fk1", new TableField[] { Homepushapplication.HOMEPUSHAPPLICATION.COMPANYID }, true);
        public static final ForeignKey<HomepushapplicationRecord, AdminaccountRecord> HOMEPUSHAPPLICATION_FK3 = Internal.createForeignKey(Keys.KEY_ADMINACCOUNT_PRIMARY, Homepushapplication.HOMEPUSHAPPLICATION, "HomePushApplication_fk3", new TableField[] { Homepushapplication.HOMEPUSHAPPLICATION.HANDLEADMINID }, true);
        public static final ForeignKey<HomepushapplicationRecord, JobofferRecord> HOMEPUSHAPPLICATION_FK2 = Internal.createForeignKey(Keys.KEY_JOBOFFER_PRIMARY, Homepushapplication.HOMEPUSHAPPLICATION, "HomePushApplication_fk2", new TableField[] { Homepushapplication.HOMEPUSHAPPLICATION.JOBOFFERID }, true);
        public static final ForeignKey<JobofferRecord, CompanyaccountRecord> JOBOFFER_FK1 = Internal.createForeignKey(Keys.KEY_COMPANYACCOUNT_PRIMARY, Joboffer.JOBOFFER, "JobOffer_fk1", new TableField[] { Joboffer.JOBOFFER.COMPANY }, true);
        public static final ForeignKey<JobofferRecord, ProfessiontypeRecord> JONOFFER_FK2 = Internal.createForeignKey(Keys.KEY_PROFESSIONTYPE_PRIMARY, Joboffer.JOBOFFER, "JonOffer_fk2", new TableField[] { Joboffer.JOBOFFER.PROFESSIONTYPE }, true);
        public static final ForeignKey<JobofferRecord, ProfessionpositionRecord> POSITION = Internal.createForeignKey(Keys.KEY_PROFESSIONPOSITION_PRIMARY, Joboffer.JOBOFFER, "position", new TableField[] { Joboffer.JOBOFFER.POSITION }, true);
        public static final ForeignKey<ResumeRecord, UseraccontRecord> RESUME_FK1 = Internal.createForeignKey(Keys.KEY_USERACCONT_PRIMARY, Resume.RESUME, "Resume_fk1", new TableField[] { Resume.RESUME.USERID }, true);
        public static final ForeignKey<ResumeRecord, JobofferRecord> RESUME_FK2 = Internal.createForeignKey(Keys.KEY_JOBOFFER_PRIMARY, Resume.RESUME, "Resume_fk2", new TableField[] { Resume.RESUME.JOBID }, true);
        public static final ForeignKey<ResumeRecord, EducationRecord> RESUME_FK3 = Internal.createForeignKey(Keys.KEY_EDUCATION_PRIMARY, Resume.RESUME, "Resume_fk3", new TableField[] { Resume.RESUME.EDUCATION }, true);
        public static final ForeignKey<UserdetailinfoRecord, UseraccontRecord> USERDETAILINFO_FK1 = Internal.createForeignKey(Keys.KEY_USERACCONT_PRIMARY, Userdetailinfo.USERDETAILINFO, "UserDetailInfo_fk1", new TableField[] { Userdetailinfo.USERDETAILINFO.ACCOUNT }, true);
    }
}
