/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen;


import com.doteadore.recruitment_backend.codegen.tables.Adminaccount;
import com.doteadore.recruitment_backend.codegen.tables.Comment;
import com.doteadore.recruitment_backend.codegen.tables.Companyaccount;
import com.doteadore.recruitment_backend.codegen.tables.Education;
import com.doteadore.recruitment_backend.codegen.tables.Homepush;
import com.doteadore.recruitment_backend.codegen.tables.Homepushapplication;
import com.doteadore.recruitment_backend.codegen.tables.Joboffer;
import com.doteadore.recruitment_backend.codegen.tables.Professionposition;
import com.doteadore.recruitment_backend.codegen.tables.Professiontype;
import com.doteadore.recruitment_backend.codegen.tables.Resume;
import com.doteadore.recruitment_backend.codegen.tables.Resumestate;
import com.doteadore.recruitment_backend.codegen.tables.Useraccont;
import com.doteadore.recruitment_backend.codegen.tables.Userdetailinfo;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Recruitment extends SchemaImpl {

    private static final long serialVersionUID = 645902646;

    /**
     * The reference instance of <code>Recruitment</code>
     */
    public static final Recruitment RECRUITMENT = new Recruitment();

    /**
     * The table <code>Recruitment.AdminAccount</code>.
     */
    public final Adminaccount ADMINACCOUNT = Adminaccount.ADMINACCOUNT;

    /**
     * The table <code>Recruitment.Comment</code>.
     */
    public final Comment COMMENT = Comment.COMMENT;

    /**
     * The table <code>Recruitment.CompanyAccount</code>.
     */
    public final Companyaccount COMPANYACCOUNT = Companyaccount.COMPANYACCOUNT;

    /**
     * The table <code>Recruitment.Education</code>.
     */
    public final Education EDUCATION = Education.EDUCATION;

    /**
     * The table <code>Recruitment.HomePush</code>.
     */
    public final Homepush HOMEPUSH = Homepush.HOMEPUSH;

    /**
     * The table <code>Recruitment.HomePushApplication</code>.
     */
    public final Homepushapplication HOMEPUSHAPPLICATION = Homepushapplication.HOMEPUSHAPPLICATION;

    /**
     * The table <code>Recruitment.JobOffer</code>.
     */
    public final Joboffer JOBOFFER = Joboffer.JOBOFFER;

    /**
     * The table <code>Recruitment.ProfessionPosition</code>.
     */
    public final Professionposition PROFESSIONPOSITION = Professionposition.PROFESSIONPOSITION;

    /**
     * The table <code>Recruitment.ProfessionType</code>.
     */
    public final Professiontype PROFESSIONTYPE = Professiontype.PROFESSIONTYPE;

    /**
     * The table <code>Recruitment.Resume</code>.
     */
    public final Resume RESUME = Resume.RESUME;

    /**
     * The table <code>Recruitment.ResumeState</code>.
     */
    public final Resumestate RESUMESTATE = Resumestate.RESUMESTATE;

    /**
     * The table <code>Recruitment.UserAccont</code>.
     */
    public final Useraccont USERACCONT = Useraccont.USERACCONT;

    /**
     * The table <code>Recruitment.UserDetailInfo</code>.
     */
    public final Userdetailinfo USERDETAILINFO = Userdetailinfo.USERDETAILINFO;

    /**
     * No further instances allowed
     */
    private Recruitment() {
        super("Recruitment", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Adminaccount.ADMINACCOUNT,
            Comment.COMMENT,
            Companyaccount.COMPANYACCOUNT,
            Education.EDUCATION,
            Homepush.HOMEPUSH,
            Homepushapplication.HOMEPUSHAPPLICATION,
            Joboffer.JOBOFFER,
            Professionposition.PROFESSIONPOSITION,
            Professiontype.PROFESSIONTYPE,
            Resume.RESUME,
            Resumestate.RESUMESTATE,
            Useraccont.USERACCONT,
            Userdetailinfo.USERDETAILINFO);
    }
}
