/*
 * This file is generated by jOOQ.
 */
package com.doteadore.recruitment_backend.codegen;


import com.doteadore.recruitment_backend.codegen.tables.Adminaccount;
import com.doteadore.recruitment_backend.codegen.tables.Comment;
import com.doteadore.recruitment_backend.codegen.tables.Companyaccount;
import com.doteadore.recruitment_backend.codegen.tables.Education;
import com.doteadore.recruitment_backend.codegen.tables.Homepush;
import com.doteadore.recruitment_backend.codegen.tables.Homepushapplication;
import com.doteadore.recruitment_backend.codegen.tables.Joboffer;
import com.doteadore.recruitment_backend.codegen.tables.Professionposition;
import com.doteadore.recruitment_backend.codegen.tables.Professiontype;
import com.doteadore.recruitment_backend.codegen.tables.Resume;
import com.doteadore.recruitment_backend.codegen.tables.Resumestate;
import com.doteadore.recruitment_backend.codegen.tables.Useraccont;
import com.doteadore.recruitment_backend.codegen.tables.Userdetailinfo;


/**
 * Convenience access to all tables in Recruitment
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>Recruitment.AdminAccount</code>.
     */
    public static final Adminaccount ADMINACCOUNT = Adminaccount.ADMINACCOUNT;

    /**
     * The table <code>Recruitment.Comment</code>.
     */
    public static final Comment COMMENT = Comment.COMMENT;

    /**
     * The table <code>Recruitment.CompanyAccount</code>.
     */
    public static final Companyaccount COMPANYACCOUNT = Companyaccount.COMPANYACCOUNT;

    /**
     * The table <code>Recruitment.Education</code>.
     */
    public static final Education EDUCATION = Education.EDUCATION;

    /**
     * The table <code>Recruitment.HomePush</code>.
     */
    public static final Homepush HOMEPUSH = Homepush.HOMEPUSH;

    /**
     * The table <code>Recruitment.HomePushApplication</code>.
     */
    public static final Homepushapplication HOMEPUSHAPPLICATION = Homepushapplication.HOMEPUSHAPPLICATION;

    /**
     * The table <code>Recruitment.JobOffer</code>.
     */
    public static final Joboffer JOBOFFER = Joboffer.JOBOFFER;

    /**
     * The table <code>Recruitment.ProfessionPosition</code>.
     */
    public static final Professionposition PROFESSIONPOSITION = Professionposition.PROFESSIONPOSITION;

    /**
     * The table <code>Recruitment.ProfessionType</code>.
     */
    public static final Professiontype PROFESSIONTYPE = Professiontype.PROFESSIONTYPE;

    /**
     * The table <code>Recruitment.Resume</code>.
     */
    public static final Resume RESUME = Resume.RESUME;

    /**
     * The table <code>Recruitment.ResumeState</code>.
     */
    public static final Resumestate RESUMESTATE = Resumestate.RESUMESTATE;

    /**
     * The table <code>Recruitment.UserAccont</code>.
     */
    public static final Useraccont USERACCONT = Useraccont.USERACCONT;

    /**
     * The table <code>Recruitment.UserDetailInfo</code>.
     */
    public static final Userdetailinfo USERDETAILINFO = Userdetailinfo.USERDETAILINFO;
}
